### ISSUE TITLE
Should warn about specifying dynamic BlendConstant when no blend factors use it

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-LoaderAndValidationLayers#248] opened 2016-04-02 13:49 UTC
When using only blend factors like VK_BLEND_FACTOR_ONE in a pipeline and not VK_BLEND_FACTOR_CONSTANT_COLOR or CONSTANT_ALPHA, specifying VK_DYNAMIC_STATE_BLEND_CONSTANTS should warn, as any dynamic value would go unused.

Alternatively, the validation should not warn about not calling vkCmdSetBlendConstants before a draw using a pipeline with DYNAMIC_STATE_BLEND_CONSTANT if CONSTANT_COLOR or CONSTANT_ALPHA is not used. 

Not sure which option is best, but I think at least one of these should be applied.

**Comment by tobine** [comment] 2016-04-04 14:40
I consider this a dupe of #195 that was recently fixed by #205 
The solution took the second option which is to only flag an error on various dynamic states if the conditions exist in the bound pipeline that would cause the dynamic state to be used, but the state is not set either statically by the pipeline nor dynamically by a vkCmdSet* call.

I don't like warning in the case when a dynamic state is set but not used b/c it may be set at the start of cmd buffer that uses multiple pipelines for various draws, and perhaps only some of those pipelines need the dynamic state.

**Closed by tobine** 2016-04-04 14:40 UTC

**Comment by hrydgard** [comment] 2016-04-04 18:48
Thanks, yes definitely a dupe, didn't see that one, sorry. I'm perfectly fine with the second option.
