### ISSUE TITLE
Building on ARM fails with latest code

### ISSUE THREAD

**Issue by sashinde** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1890] opened 2017-06-19 11:33 UTC
There are errors while building loader and tools for ARM architecture. 

The error are introduced with commit: 1b88cb983ece32b88bea4d5ee5b107e53705a226 which has x86 specific code and not available for ARM.

By reverting 1b88cb983ece32b88bea4d5ee5b107e53705a226, I'm able to build loader 1.0.51 properly.

Please fix this.

**Comment by lenny-lunarg** [comment] 2017-06-19 16:54
What command line instructions are you using to build for ARM? The goal in that commit was to leave behind the old C code, and to enable it if the platform wasn't x86. So it sounds like the configuration isn't working, but to address it I need to know how you're building the repo.

**Comment by leigh123linux** [comment] 2017-06-20 23:17
1.0.51 built ok on linux arm

https://koji.fedoraproject.org/koji/buildinfo?buildID=908767

**Comment by lenny-lunarg** [comment] 2017-06-21 15:43
The commit mentioned by @sashinde was actually put into master just after we branched for the 1.0.51.0 SDK (because we foresaw potential problems). As a result, the error happens with code still using the 1.0.51 header, but it's really from after the SDK. Building from the `sdk-1.0.51.0` tag shouldn't have the commit in it, which may be the reason why fedora had no trouble with arm.

In any case, I still need to know how to reproduce this error before I can do a whole lot for this issue.

**Comment by leigh123linux** [comment] 2017-06-24 06:34
@lenny-lunarg I still can't reproduce any build issues building git snapshot of https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/1b88cb983ece32b88bea4d5ee5b107e53705a226

https://koji.fedoraproject.org/koji/taskinfo?taskID=20134740

**Comment by leigh123linux** [comment] 2017-06-24 07:05
@lenny-lunarg  Building the latest git fails on all non x86 builds with ASM errors.

https://koji.fedoraproject.org/koji/taskinfo?taskID=20135113

buildlogs for failed builds

https://leigh123linux.fedorapeople.org/pub/buildlogs/vulkan/

**Comment by rockyrhodes** [comment] 2017-06-29 17:31
The problem is that on some arm systems the test "if (CMAKE_ASM-ATT_COMPILER_WORKS)" passes.  ${CMAKE_SYSTEM_PROCESSOR} should also be verified to match "i.86" before utilizing the x86 asm code.

**Comment by lenny-lunarg** [comment] 2017-06-29 21:53
I don't entirely like the `${CMAKE_SYSTEM_PROCESSOR}` fix because means you can't build on one architecture, for use on another. I've pushed a fix to a branch on this repo called `lenny_asm_archs` (commit 0f32cbc3cc1875a3a4137b8684644703b0eb354a). This change runs the assembler on a small test file, and checks if that succeeded to determine whether or not the assembler is suitable. My only real concern is that this doesn't work on Windows. My hope is that Windows is a non-issue, since MASM only works on x86, but I don't have a good way to test this.

@leigh123linux, is it easy for you to run those builds off the `lenny_asm_archs` branch? Because I don't have any system that can build for arm right now, so if you could build the branch to see if it works, that would let me know that this works and I can merge it into master.

**Comment by leigh123linux** [comment] 2017-06-29 22:26
@lenny-lunarg 

lenny_asm_archs https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/0f32cbc3cc1875a3a4137b8684644703b0eb354a builds on all arch 

https://koji.fedoraproject.org/koji/taskinfo?taskID=20254509

**Comment by lenny-lunarg** [comment] 2017-06-30 22:27
This issue should now be resolved on master via the pull request shown above.

**Closed by lenny-lunarg** 2017-06-30 22:27 UTC
Labels: bug
