### ISSUE TITLE
Report names, associated with VK objects via EXT_debug_marker, if provided by app.

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2134] opened 2017-10-16 07:28 UTC
Consider below example validation error:

``
vkCmdDraw(): Cannot use image 0x12ef05e0 with specific layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL that doesn't match the actual current layout VK_IMAGE_LAYOUT_UNDEFINED.
``

If the application associates names with Vulkan objects, which is a piece of functionality introduced with VK_EXT_debug_marker, it would be tremendously useful to include them along with handles in error messages reported by the validation layers.

**Comment by DominikWitczakAMD** [comment] 2017-10-16 10:34
It would be super-useful if the names could also be included with handles outputted by the api dump layer.

**Comment by mark-lunarg** [comment] 2017-10-16 15:10
@DominikWitczakAMD, this is a duplicate of #2107, and this is currently assigned to be done in the near future.

**Closed by mark-lunarg** 2017-10-16 15:10 UTC
Labels: enhancement
