### ISSUE TITLE
No message from VK_LAYER_LUNARG_standard_validation when submitting an invalid command buffer to VkQueueSubmit

### ISSUE THREAD

**Issue by NTimmons** [KhronosGroup/Vulkan-LoaderAndValidationLayers#812] opened 2016-08-02 15:55 UTC
When submitting a 'VKCommandBuffer' that has been created from a VkCommandPool with the mismatching queueFamilyIndex, VkQueueSubmit will return an invalid error code (_VK_ERROR_INITIALIZATION_FAILED on the implementation I am using_) but will not output a validation message.

**Comment by lentinem** [comment] 2016-08-02 16:02
Duplicate of #790

**Closed by lentinem** 2016-08-02 16:02 UTC

**Comment by NTimmons** [comment] 2016-08-02 16:05
Apologies for the duplicate, didnt spot the other. 

Thanks
