### ISSUE TITLE
Device extension entry points show up as instance entry points.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#662] opened 2016-06-19 15:56 UTC
If you have a device extension which adds the following entry point:

    "device_extensions": [
        {
            "entrypoints": [ "vkCallMe" ]
        }
    ],

Then you can do:

    typedef void (VKAPI_PTR *PFN_vkCallMe)();

    PFN_vkCallMe vkCallMe = (PFN_vkCallMe) vkGetInstanceProcAddr( instance, "vkCallMe" );
    if ( vkCallMe != NULL )
    {
        vkCallMe(); // crash
    }

vkCallMe is now unequal NULL but typically a bad pointer which will result in a crash when used.

**Comment by Pernet** [comment] 2016-06-19 17:05
[https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#initialization-functionpointers](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#initialization-functionpointers)

> Function pointers for all Vulkan commands can be obtained with the command vkGetInstanceProcAddr

Function vkCallMe (1) returned by vkGet**Device**ProcAddr is a Vulkan command, so vkGet**Instance**ProcAddr MUST return a valid function vkCallMe (2) too.

> In order to support systems with multiple Vulkan implementations comprising heterogeneous collections of hardware and software, the function pointers returned by vkGetInstanceProcAddr may point to dispatch code, which calls a different real implementation for different VkDevice objects (and objects created from them). The overhead of this internal dispatch can be avoided by obtaining device-specific function pointers for any commands that use a device or device-child object as their dispatchable object. Such function pointers can be obtained with the command:

Function vkCallMe (1) returned by vkGet**Device**ProcAddr MAY be different from function vkCallMe (2) returned by vkGet**Instance**ProcAddr.

Conclusion : if (1) exists, (2) MUST exists, but is implementation specific.

**Comment by mre4ce** [comment] 2016-06-19 17:24
I guess this should be classified as an incorrect layer implementation because in the manifest it claims to add device entry points but the actual entry points are not implemented. Instead of just returning NULL the loader returns an invalid pointer.

**Comment by courtney-g** [comment] 2016-06-20 16:57
Which layer is causing this?

**Comment by mre4ce** [comment] 2016-06-20 19:00
I ran into issues while writing a sample that adds an instance extension with a new entry point. Because things didn't work I started going through the loader code to see if there would be a way to make it work without having to make any loader changes. That's how I ran into this case, where the manifest JSON advocates new device entry points that are not actually implemented, which results in getting an invalid pointer through vkGetInstanceProcAddr. This makes the layer implementation incorrect, but it would be nice if the loader would print a warning/error and return a NULL pointer.

**Comment by courtney-g** [comment] 2016-06-20 20:26
Okay, I see.

The issue is that the layer has not implemented a function it declares in it's json file. I think that would be considered a bug in the layer and the layer's responsibility to fix. In the name of performance, validating input, for the most part, is something Vulkan avoids.

Does make me wonder about a layer that validates other layers. If a lot of people start implementing layers we may want to do that.

**Comment by MarkY-LunarG** [comment] 2016-06-20 20:35
I agree, that sounds like a good idea, Courtney.  Don't we have a unified TODO list somewhere, or is it just now GitHub issues?

**Comment by mre4ce** [comment] 2016-06-20 22:01
That sounds like a good idea. It is often unclear why the load does what it does or does not do what you want it to do. I understand the desire to do minimal error checking for performance reasons but I would hope vkGetInstanceProdAddr is not on a performance critical path. Either way, having a layer that validates other layers would avoid any performance concerns.

**Comment by courtney-g** [comment] 2016-06-20 22:33
@tobine - Is a validation layer that validates other layers something that should go on the validation TODO list?

In general, things like this should be make as feature requests via Github issues and it will migrate to where it's needed.

**Comment by tobine** [comment] 2016-06-20 22:45
An issue could certainly be created in this GitHub to track request for a layer to validate other layers.

For the specific bug being discussed here, an alternative to the layer-validate-layer approach is to standardize on layer development tools. Note that @olvaffe added vk-layer-introspect to this repo, which will generate correct json for a given layer library, and I believe would have avoided the initial issue reported here. Promoting, publishing, and improving that tool may be the best long-term solution.

**Comment by MarkY-LunarG** [comment] 2016-06-21 14:41
I created Issue #671 to track the idea of a layer to validate other layers.  I've labeled it as a Feature and Enhancement for now.

**Comment by MarkY-LunarG** [comment] 2016-06-23 20:09
Can we close this issue as a user created layer bug?  Or was there something else to cover here?

**Comment by jon-lunarg** [comment] 2016-06-28 19:22
Reopen if needed.

**Closed by jon-lunarg** 2016-06-28 19:22 UTC
Labels: help wanted
