### ISSUE TITLE
pTessellationState in pipeline create should be ignored if tessellation isn't used

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1672] opened 2017-04-17 10:49 UTC
The [current code](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/layers/core_validation.cpp#L3253-L3266) for validating tessellation state (e.g. checking if the `patchControlPoints` value is valid) always runs, even if the pipeline doesn't use tessellation.

The spec says (emphasis mine):

> pTessellationState is a pointer to an instance of the VkPipelineTessellationStateCreateInfo structure, **and is ignored if the pipeline does not include a tessellation control shader stage and tessellation evaluation shader stage.**

**Comment by mark-lunarg** [comment] 2017-04-18 21:31
This is a duplicate of issue #1411.  Progress will be tracked through this existing issue.  Thanks!

**Closed by mark-lunarg** 2017-04-18 21:31 UTC
Labels: bug
