### ISSUE TITLE
Cube no longer compiles

### ISSUE THREAD

**Issue by FireBurn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1190] opened 2016-11-23 09:52 UTC
Cube no longer compiles

/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2598:17: error: redeclaration of ‘wl_display* Demo::display’
     wl_display *display;
                 ^~~~~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2589:14: note: previous declaration ‘Display* Demo::display’
     Display *display;
              ^~~~~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp: In constructor ‘Demo::Demo()’:
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2594:23: warning: ‘Demo::connection’ will be initialized after [-Wreorder]
     xcb_connection_t *connection;
                       ^~~~~~~~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:2589:14: warning:   ‘Display* Demo::display’ [-Wreorder]
     Display *display;
              ^~~~~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:208:5: warning:   when initialized here [-Wreorder]
     Demo()
     ^~~~
/var/tmp/portage/media-libs/vulkan-base-9999/work/vulkan-base-9999/demos/cube.cpp:208:5: error: multiple initializations given for ‘Demo::display’

**Comment by mark-lunarg** [comment] 2016-11-23 15:02
@FireBurn, can you provide more information please -- what is your build configuration/platform/etc., which commit/SDK version are you at?

**Comment by FireBurn** [comment] 2016-11-23 15:07
Hi

I'm on Gentoo Linux  gcc-6.2.0, glibc-2.23-r3, 4.9.0-rc4-agd5f+ x86_64

That's running git head for the following repos:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git
https://github.com/KhronosGroup/glslang.git
https://github.com/KhronosGroup/SPIRV-Tools.git
https://github.com/KhronosGroup/SPIRV-Headers.git
https://github.com/google/googletest.git

The last time I recompiled everything was 15th Nov

**Comment by mark-lunarg** [comment] 2016-11-23 15:10
Super, thanks.  Do you happen to know which displayserver(s) you are building for?  Is this Xcb-only?

**Comment by FireBurn** [comment] 2016-11-23 15:11
Here's the build log http://pastebin.com/j4GspFjx

**Comment by FireBurn** [comment] 2016-11-23 15:13
With the options:

                -DBUILD_WSI_XCB_SUPPORT=ON      \
                -DBUILD_WSI_XLIB_SUPPORT=ON     \
                -DBUILD_WSI_WAYLAND_SUPPORT=ON  \
                -DBUILD_WSI_MIR_SUPPORT=OFF     \
                -DBUILD_VKJSON=OFF              \
                -DBUILD_LOADER=ON               \
                -DBUILD_LAYERS=ON               \
                -DBUILD_DEMOS=ON                \
                -DBUILD_TESTS=ON                \
                -H. -Bbuild

**Comment by mark-lunarg** [comment] 2016-11-23 15:15
Thanks Mike!  We'll look into it shortly.

**Comment by FireBurn** [comment] 2016-11-23 15:15
What does DBUILD_VKJSON control?

**Comment by mark-lunarg** [comment] 2016-11-23 15:22
Whether or not the vkjson stuff gets built.  This is a json library which (I believe) is not being actively used at the moment.

**Comment by karl-lunarg** [comment] 2016-11-23 17:44
This was probably caused by some recent changes to get all the permutations of -DBUILD_WSI_XCB_SUPPORT and -DBUILD_WSI_XLIB_SUPPORT working.
Wayland configs need to get added to our CI builds. ( @lenny-lunarg )
Let's not close this issue until the CI machines are building configs that include Wayland.

**Closed** 2016-11-24 00:16 UTC
Labels: bug
