### ISSUE TITLE
Refactor QueueSubmit to only update state when submit occurs

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-LoaderAndValidationLayers#990] opened 2016-09-28 16:31 UTC
Need to partition QueueSubmit core_validation work into "PreValidate" and "PostUpdate" sections so that state is only updated if the call isn't skipped.

**Comment by chrisforbes** [comment] 2016-09-28 21:26
Dupe of #945

**Closed by chrisforbes** 2016-09-28 21:26 UTC
