### ISSUE TITLE
Resetting command pool doesn't track fences properly

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/Vulkan-LoaderAndValidationLayers#561] opened 2016-05-18 08:40 UTC
When trying to use VkCommandPool and resetting it, core validation thinks the command buffer is still in flight, while it has been waited on by a fence.

Scenario:

 - Create command pool without command buffer reset
 - Create fence
 - Allocate command buffer
 - Record cmd
 - Submit w/ fence
 - Wait for fence
 - Reset command pool
 - Begin same command buffer

Gives error:

```
MEM(ERROR): object: 0xef7840 type: 6 location: 6118 msgCode: 9: Calling vkBeginCommandBuffer() on active CB 0x0xef7840 before it has completed. You must check CB fence before this call.
```

If I reset the command buffer and use resettable command pool, it behaves as expected.
Logging suggests that the inflight command buffer set is not handled correctly with reset command pools for some unknown reason.

**Comment by lentinem** [comment] 2016-05-18 13:51
Do you have a repro case we could use to test this?

**Comment by Themaister** [comment] 2016-05-18 15:43
I can reproduce it with: http://malideveloper.arm.com/resources/sdks/mali-vulkan-sdk/
and patching it to reset pool instead.

```
diff --git a/framework/command_buffer_manager.cpp b/framework/command_buffer_manager.cpp
index 05c5176..bd34831 100644
--- a/framework/command_buffer_manager.cpp
+++ b/framework/command_buffer_manager.cpp
@@ -21,7 +21,6 @@ CommandBufferManager::CommandBufferManager(VkDevice vkDevice, VkCommandBufferLev
 	// RESET_COMMAND_BUFFER_BIT allows command buffers to be reset individually.
 	VkCommandPoolCreateInfo info = { VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO };
 	info.queueFamilyIndex = graphicsQueueIndex;
-	info.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
 	VK_CHECK(vkCreateCommandPool(device, &info, nullptr, &pool));
 }
 
@@ -33,6 +32,7 @@ CommandBufferManager::~CommandBufferManager()
 
 void CommandBufferManager::beginFrame()
 {
+	vkResetCommandPool(device, pool, 0);
 	count = 0;
 }
 
@@ -43,7 +43,6 @@ VkCommandBuffer CommandBufferManager::requestCommandBuffer()
 	if (count < buffers.size())
 	{
 		ret = buffers[count++];
-		VK_CHECK(vkResetCommandBuffer(ret, VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT));
 	}
 	else
 	{
```

Build for PNG backend with `make` on Linux. Enable validation layers externally with
```
export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation
export VK_DEVICE_LAYERS=VK_LAYER_LUNARG_standard_validation
```
and the default vk_layer_settings.txt.

Run `samples/rotating_texture/rotating_texture`.

**Comment by tobine** [comment] 2016-05-18 22:42
Alright, I was able to repro this and so far I believe that the validation error that's flagged is correct.

The sequence of command that you listed is not what leads to the error. I see that same sequence and everything is fine up to that point.

At the end of your command sequence is the BeginCmdBuffer() call. What I see next is that that cmd buffer is submitted via vkQueueSubmit(). Then, without any call to QueueWaitIdle() or WaitForFences() there is another call to BeginCmdBuffer(). This is when I see the error flagged which I believe is correct at that time.

Can you double-check and verify if my findings match what you're seeing?

I did a quick check of the RESET case to see what the difference is. I see the same Begin->Submit->Begin sequence in that case w/o a WaitIdle or WaitForFences, but in that case there's no error flagged. I'll look at this further tomorrow to understand the difference. There may be a validation bug in there still.

**Comment by tobine** [comment] 2016-05-19 15:29
Alright, looked at this a bit more. I confirmed that in the RESET case the Begin->Submit->Begin sequence spans 2 different cmd buffers whereas in the no-RESET case, the same Cmd buffer is used. This is why the error is triggered in the no-RESET case but not the RESET case.

So with the ResetCommandPool() change that was made to command_buffer_manager.cpp, the code re-uses the same cmd buffer without resetting it and without a wait to make sure first submission completed.

I believe validation error is therefore correct and will close this issue. If you find differently feel free to re-open.

**Comment by Themaister** [comment] 2016-05-19 20:19
"Re-uses the same cmd without resetting it". But wouldn't ResetCommandPool reset all command buffers? It sounds wrong that no fence has been waited for as well.

Anyways, I will try to verify your findings.

**Comment by tobine** [comment] 2016-05-19 21:00
Yes, ResetCommandPool resets all of its command buffers. In the failing case, however, ResetCommandPool is not called between Begin->Submit->Begin on the same cmd buffer. In the passing case, a new cmd buffer is grabbed for the second Begin, so even though no reset happens in that case either, there is no error because it's a new command buffer.

**Comment by Themaister** [comment] 2016-05-20 08:31
I cannot reproduce the finding. I added some more logging:

```
diff --git a/framework/command_buffer_manager.cpp b/framework/command_buffer_manager.cpp
index 05c5176..2c4939f 100644
--- a/framework/command_buffer_manager.cpp
+++ b/framework/command_buffer_manager.cpp
@@ -21,7 +21,6 @@ CommandBufferManager::CommandBufferManager(VkDevice vkDevice, VkCommandBufferLev
 	// RESET_COMMAND_BUFFER_BIT allows command buffers to be reset individually.
 	VkCommandPoolCreateInfo info = { VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO };
 	info.queueFamilyIndex = graphicsQueueIndex;
-	info.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
 	VK_CHECK(vkCreateCommandPool(device, &info, nullptr, &pool));
 }
 
@@ -33,6 +32,8 @@ CommandBufferManager::~CommandBufferManager()
 
 void CommandBufferManager::beginFrame()
 {
+	fprintf(stderr, "Resetting pool 0x%llx\n", (unsigned long long)pool);
+	vkResetCommandPool(device, pool, 0);
 	count = 0;
 }
 
@@ -43,7 +44,7 @@ VkCommandBuffer CommandBufferManager::requestCommandBuffer()
 	if (count < buffers.size())
 	{
 		ret = buffers[count++];
-		VK_CHECK(vkResetCommandBuffer(ret, VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT));
+		fprintf(stderr, "Reusing command buffer 0x%llx from pool 0x%llx\n", (unsigned long long)ret, (unsigned long long)pool);
 	}
 	else
 	{
@@ -53,6 +54,7 @@ VkCommandBuffer CommandBufferManager::requestCommandBuffer()
 		info.commandBufferCount = 1;
 		VK_CHECK(vkAllocateCommandBuffers(device, &info, &ret));
 		buffers.push_back(ret);
+		fprintf(stderr, "Created command buffer 0x%llx from pool 0x%llx\n", (unsigned long long)ret, (unsigned long long)pool);
 
 		count++;
 	}
diff --git a/framework/context.cpp b/framework/context.cpp
index 5208a43..b41f310 100644
--- a/framework/context.cpp
+++ b/framework/context.cpp
@@ -104,6 +104,8 @@ void Context::submitCommandBuffer(VkCommandBuffer cmd, VkSemaphore acquireSemaph
 	info.signalSemaphoreCount = releaseSemaphore != VK_NULL_HANDLE ? 1 : 0;
 	info.pSignalSemaphores = &releaseSemaphore;
 
+	fprintf(stderr, "Submitting command buffer 0x%llx to fence 0x%llx\n", (unsigned long long)cmd, (unsigned long long)fence);
+
 	VK_CHECK(vkQueueSubmit(queue, 1, &info, fence));
 }
 }
diff --git a/framework/fence_manager.cpp b/framework/fence_manager.cpp
index 6042881..9d494ee 100644
--- a/framework/fence_manager.cpp
+++ b/framework/fence_manager.cpp
@@ -32,6 +32,10 @@ void FenceManager::beginFrame()
 	// since we're waiting for old frames to have been completed, but just in case.
 	if (count != 0)
 	{
+		for (unsigned i = 0; i < count; i++)
+		{
+			fprintf(stderr, "Waiting for fence 0x%llx\n", (unsigned long long)fences[i]);
+		}
 		vkWaitForFences(device, count, fences.data(), true, UINT64_MAX);
 		vkResetFences(device, count, fences.data());
 	}
diff --git a/platform/png/png_swapchain.cpp b/platform/png/png_swapchain.cpp
index c414f5b..842cc5c 100644
--- a/platform/png/png_swapchain.cpp
+++ b/platform/png/png_swapchain.cpp
@@ -121,6 +121,10 @@ void PNGSwapchain::threadEntry()
 			ready.pop();
 		}
 
+		for (unsigned i = 0; i < command.numFences; i++)
+		{
+			fprintf(stderr, "Waiting for fence in swapchain thread: 0x%llx\n", (unsigned long long)command.fences[i]);
+		}
 		vkWaitForFences(command.device, command.numFences, command.fences, true, UINT64_MAX);
 		unsigned nextVacant = displayed;
```

Which gives me this output. Tried a different GPU now and getting somewhat different behavior:
```
Created command buffer 0x19be770 from pool 0xd
Submitting command buffer 0x19be770 to fence 0x19
Waiting for fence 0x19
Resetting pool 0xd
Reusing command buffer 0x19be770 from pool 0xd
Submitting command buffer 0x19be770 to fence 0x19
Created command buffer 0x1924db0 from pool 0xd
Submitting command buffer 0x1924db0 to fence 0x32
Resetting pool 0xe
Waiting for fence in swapchain thread: 0x19
Waiting for fence in swapchain thread: 0x32
Created command buffer 0x19f3920 from pool 0xe
INFO: Writing PNG file to: "Mali-SDK-Frames.00000000.png".
Submitting command buffer 0x19f3920 to fence 0x33
Created command buffer 0x1901190 from pool 0xe
Submitting command buffer 0x1901190 to fence 0x34
Resetting pool 0xf
Created command buffer 0x19371a0 from pool 0xf
Submitting command buffer 0x19371a0 to fence 0x35
Created command buffer 0x1a186c0 from pool 0xf
Submitting command buffer 0x1a186c0 to fence 0x36
INFO: Wrote PNG file: "Mali-SDK-Frames.00000000.png".
Waiting for fence in swapchain thread: 0x33
Waiting for fence in swapchain thread: 0x34
INFO: Writing PNG file to: "Mali-SDK-Frames.00000001.png".
INFO: Wrote PNG file: "Mali-SDK-Frames.00000001.png".
Waiting for fence in swapchain thread: 0x35
Waiting for fence in swapchain thread: 0x36
Waiting for fence 0x19
Waiting for fence 0x32
INFO: Writing PNG file to: "Mali-SDK-Frames.00000002.png".
DS(ERROR): object: 0x19 type: 7 location: 5431 msgCode: 15: Fence 0x19 is in use by a command buffer.
DS(ERROR): object: 0x32 type: 7 location: 5431 msgCode: 15: Fence 0x32 is in use by a command buffer.
Resetting pool 0xd
DS(ERROR): object: 0x19be770 type: 6 location: 5286 msgCode: 54: Attempt to reset command pool with command buffer (0x19be770) which is in use.
DS(ERROR): object: 0x1924db0 type: 6 location: 5286 msgCode: 54: Attempt to reset command pool with command buffer (0x1924db0) which is in use.
Reusing command buffer 0x19be770 from pool 0xd
```

The interesting bit is this:
```
Created command buffer 0x19be770 from pool 0xd
Submitting command buffer 0x19be770 to fence 0x19
Waiting for fence 0x19
Resetting pool 0xd
Reusing command buffer 0x19be770 from pool 0xd
Submitting command buffer 0x19be770 to fence 0x19
...
Waiting for fence in swapchain thread: 0x19
...
Waiting for fence 0x19
...
Resetting pool 0xd
DS(ERROR): object: 0x19be770 type: 6 location: 5286 msgCode: 54: Attempt to reset command pool with command buffer (0x19be770) which is in use.
DS(ERROR): object: 0x1924db0 type: 6 location: 5286 msgCode: 54: Attempt to reset command pool with command buffer (0x1924db0) which is in use.
Reusing command buffer 0x19be770 from pool 0xd
MEM(ERROR): object: 0x19be770 type: 6 location: 6114 msgCode: 9: Calling vkBeginCommandBuffer() on active CB 0x0x19be770 before it has completed. You must check CB fence before this call.
```

I can't see any wrong usage from the logs. The fence 0x19 has been waited for and the command pool is reset.

**Comment by Themaister** [comment] 2016-05-21 14:08
For some reason, reopening the issue doesn't work.

**Comment by tobine** [comment] 2016-05-23 19:37
Hello,
I've re-run with your updated logging. I'm also using the latest validation code (HEAD of master branch) as of right now. My results are below. You can see that my results are slightly different than yours, which I suspect is a combination of running on different hardware, and also having more recent validation code.
In any event, I see three separate validation errors in the sequence below:

1. Calling vkBeginCommandBuffer() on active CB 0x0x90a280...
2. Command Buffer 0x90a280 is already in use...
3. Call to vkBeginCommandBuffer() on command buffer (0x90a280) attempts to implicitly reset...

In all cases you can see that for my run the same CB handle is being used in a sequence without either that CB or it's Pool being reset from one submit to another. Therefore the errors that I'm seeing appear correct.

I agree that the trace that you reported looks suspect, but my suspicion is that there are bug fixes in the latest validation code that you're not running with.

If you can run with the latest validation code from GitHub, that would confirm if your issues have been fixed. LunarG also released a new SDK at the end of last week that may have all the fixes you need.

> Created command buffer 0x90a280 from pool 0xd
Submitting command buffer 0x90a280 to fence 0x19
Waiting for fence 0x19
Resetting pool 0xd
Reusing command buffer 0x90a280 from pool 0xd
DS(WARN): object: 0x0 type: 0 location: 7607 msgCode: 12: Additional bits in Source accessMask 0x8000 [VK_ACCESS_MEMORY_READ_BIT] are specified when layout is VK_IMAGE_LAYOUT_UNDEFINED.
Submitting command buffer 0x90a280 to fence 0x19
Created command buffer 0x90a280 from pool 0xd
MEM(ERROR): object: 0x90a280 type: 6 location: 6112 msgCode: 9: Calling vkBeginCommandBuffer() on active CB 0x0x90a280 before it has completed. You must check CB fence before this call.
Submitting command buffer 0x90a280 to fence 0x32
DS(ERROR): object: 0x0 type: 6 location: 4366 msgCode: 53: Command Buffer 0x90a280 is already in use and is not marked for simultaneous use.
Resetting pool 0xe
Waiting for fence in swapchain thread: 0x19
Waiting for fence in swapchain thread: 0x32
Created command buffer 0x18a1640 from pool 0xe
DS(WARN): object: 0x0 type: 0 location: 7607 msgCode: 12: Additional bits in Source accessMask 0x8000 [VK_ACCESS_MEMORY_READ_BIT] are specified when layout is VK_IMAGE_LAYOUT_UNDEFINED.
Submitting command buffer 0x18a1640 to fence 0x33
INFO: Writing PNG file to: "Mali-SDK-Frames.00000000.png".
Created command buffer 0x18a3e60 from pool 0xe
Submitting command buffer 0x18a3e60 to fence 0x34
Resetting pool 0xf
Created command buffer 0x18a5e70 from pool 0xf
DS(WARN): object: 0x0 type: 0 location: 7607 msgCode: 12: Additional bits in Source accessMask 0x8000 [VK_ACCESS_MEMORY_READ_BIT] are specified when layout is VK_IMAGE_LAYOUT_UNDEFINED.
Submitting command buffer 0x18a5e70 to fence 0x35
Created command buffer 0x18c9fe0 from pool 0xf
Submitting command buffer 0x18c9fe0 to fence 0x36
INFO: Wrote PNG file: "Mali-SDK-Frames.00000000.png".
Waiting for fence in swapchain thread: 0x33
Waiting for fence in swapchain thread: 0x34
INFO: Writing PNG file to: "Mali-SDK-Frames.00000001.png".
INFO: Wrote PNG file: "Mali-SDK-Frames.00000001.png".
Waiting for fence in swapchain thread: 0x35
Waiting for fence in swapchain thread: 0x36
Waiting for fence 0x19
Waiting for fence 0x32
INFO: Writing PNG file to: "Mali-SDK-Frames.00000002.png".
Resetting pool 0xd
Reusing command buffer 0x90a280 from pool 0xd
DS(WARN): object: 0x0 type: 0 location: 7607 msgCode: 12: Additional bits in Source accessMask 0x8000 [VK_ACCESS_MEMORY_READ_BIT] are specified when layout is VK_IMAGE_LAYOUT_UNDEFINED.
Submitting command buffer 0x90a280 to fence 0x19
Reusing command buffer 0x90a280 from pool 0xd
MEM(ERROR): object: 0x90a280 type: 6 location: 6112 msgCode: 9: Calling vkBeginCommandBuffer() on active CB 0x0x90a280 before it has completed. You must check CB fence before this call.
DS(ERROR): object: 0x90a280 type: 6 location: 6203 msgCode: 54: Call to vkBeginCommandBuffer() on command buffer (0x90a280) attempts to implicitly reset cmdBuffer created from command pool (0xd) that does NOT have the VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT bit set.
Submitting command buffer 0x90a280 to fence 0x32
DS(ERROR): object: 0x0 type: 6 location: 4366 msgCode: 53: Command Buffer 0x90a280 is already in use and is not marked for simultaneous use.
INFO: Wrote PNG file: "Mali-SDK-Frames.00000002.png".
Waiting for fence in swapchain thread: 0x19
Waiting for fence in swapchain thread: 0x32

**Comment by Themaister** [comment] 2016-05-23 21:11
Hm ...
```
Submitting command buffer 0x90a280 to fence 0x19
Created command buffer 0x90a280 from pool 0xd
```
I see. Now this explains some things. That is actually a driver bug. At least one vendor is known to misimplement ResetCommandPool where it will free the command buffers instead of just resetting (reported). That would make the next AllocateCommandBuffers grab the currently active command buffer and trigger validation errors. That explains your earlier findings as well where Reset gave you the same command buffer twice in a row.

**Comment by tobine** [comment] 2016-07-01 20:56
This should all be correct from a validation standpoint now, closing. @Themaister please let me know if you find differently. Note that in addition to some original validation fixes for cmd buffer reset handling, the fence tracking code has been greatly overhauled recently with a number of bugs fixed.

**Closed by tobine** 2016-07-01 20:56 UTC
Labels: bug
