### ISSUE TITLE
DrawState layer: "Cannot delete semaphore X which is in use" error incorrectly reported

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#100] opened 2016-03-10 10:12 UTC
In principle, this issue builds upon #99.

The two command buffers we submit with a single vkQueueSubmit() call are synchronized as per my last comment in #67. tl;dr: the first cmd buffer signals a semaphore A, and the second cmd buffer waits on it before executing. We then submit both command buffers, wait on a fence passed with the vkQueueSubmit() call and proceed with releasing the objects.

At this point, when I call vkDeleteSemaphore(), I'm getting a misleading debug call-back informing me the semaphore is still in use. Here's the obligatory call stack:

![image](https://cloud.githubusercontent.com/assets/17761066/13666257/e2cd6fac-e6b0-11e5-9cf3-4a157d3be6a6.png)

**Comment by lentinem** [comment] 2016-03-10 15:42
Will try to find something obvious but will likely need a more solid repro for this.

**Comment by lentinem** [comment] 2016-03-10 18:52
This is likely fixed by 110 as well.

**Comment by DominikWitczakAMD** [comment] 2016-03-11 10:17
Fixed, closing.

**Comment by DominikWitczakAMD** [comment] 2016-03-11 10:44
Managed to reproduce the error in a different scenario:

1. Create a semaphore A.
2. Submit a command buffer with the semaphore used as a signal semaphore.
3. Submit another command buffer, with the semaphore used this time as a wait semaphore.
4. Destroy the semaphore.

This results in the same "Cannot delete semaphore X which is in use" error being reported.

**Comment by DominikWitczakAMD** [comment] 2016-03-16 09:19
Potentially related to #134

**Comment by lentinem** [comment] 2016-03-18 14:42
Were these the same queues or different queues? If they were the same brief testing did not repro. If they were different then it should be the same issue as #99.

**Comment by DominikWitczakAMD** [comment] 2016-03-22 16:12
The issue continues to reproduce, I'm afraid. Just to ensure we're talking about the same scenario, here's how I'm getting that call-back:

1. Submit a command buffer 1 to a compute queue family. Use semaphore A as a signal semaphore here.
2. Submit a command buffer 2 to a universal queue family. Use the semaphore A as a wait signal in this step (along with a relevant dst stage mask). Also use a fence X here.
3. Wait for fence X to be set.
4. Destroy command buffer 1

**Comment by lentinem** [comment] 2016-03-24 03:04
Just to clarify; are you still using draw state or have you switched to core_validation?

**Comment by DominikWitczakAMD** [comment] 2016-03-29 10:51
Switched to core_validation. I always sync to the latest master version before trying to reproduce any of the reported issues.

**Comment by DominikWitczakAMD** [comment] 2016-03-30 10:40
Continues to reproduce with the latest version from master (3d3e06b40a06f099e741b9299efa66bddb69a074 )

**Comment by lentinem** [comment] 2016-03-30 14:38
Same as #99

**Comment by mark-lunarg** [comment] 2016-04-01 14:16
Coincidentally, just a few days ago we received an identical LunarXchange issue, #459.  We'll get it up on our AMD box today.

**Comment by mark-lunarg** [comment] 2016-04-01 20:20
See Pull Request #245.  I didn't get Dominik's app to work, but we wrote one here and this fix passes that test plus Niko's test app (from LunarXchange) and all current tests here.

**Comment by DominikWitczakAMD** [comment] 2016-04-04 08:02
This problem continues to reproduce, perhaps due to the following situation:

![image](https://cloud.githubusercontent.com/assets/17761066/14241501/dfee5176-fa4b-11e5-93e8-63cd73661bf2.png)

It appears that now the in_use counter is decremented even after it reaches 0 which causes it to wrap to ~0, which in turns leads to the same debug call-back. I don't think this is what was happening last week.

**Comment by mark-lunarg** [comment] 2016-04-04 16:01
Hey Dominik -- If source code is not possible, is there any way you can use the api_dump layer to get us a dump of the app up until the error shows?

**Comment by DominikWitczakAMD** [comment] 2016-04-05 06:40
For the record: subsequent discussion moved to an e-mail thread.

**Comment by mark-lunarg** [comment] 2016-04-21 14:42
Dominik -- this should be taken care of by PR 400 when it lands.  Thanks for your patience.

**Closed by mark-lunarg** 2016-04-21 14:42 UTC
Labels: bug

**Comment by mre4ce** [comment] 2016-04-21 19:57
I was getting the same error for a present semaphore. Using latest master I am unable to reproduce this problem.
