### ISSUE TITLE
Core validation layer causes exception in swapchain layer when destroying debug callback

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-LoaderAndValidationLayers#487] opened 2016-05-05 17:16 UTC
I am getting an Exception from the swapchain validation layer that tries to destroy the debug callback that has been assigned by the application. I've had this before, but never had the time to dig into it, but I can now reproduce this and think I found the reason behind this.

If validation is enabled, my Vulkan example base sets up debugging and creates the debug message callback before creating any other Vulkan resources, this includes the swap chain. 

I', using the "VK_LAYER_LUNARG_standard_validation" meta validation layer name to include all the relevant validation layers in the right order, this also includes the swap chain and the core validation layers.

Calling vkDestroyDebugReportCallback then throws an exception inside the swapchain layer :

![image](https://cloud.githubusercontent.com/assets/10283127/15050461/412e93c2-12f4-11e6-944c-d2afee9f8040.png)

The exception happens inside vkDestroyDebugReportCallbackEXT :

![image](https://cloud.githubusercontent.com/assets/10283127/15050481/5c47c958-12f4-11e6-8947-6d1de6c5b516.png)

If you walk back down the call stack you can see that the problem seems to be the core validation layer that destroy the callback before the swapchain callback destructor is called :

![image](https://cloud.githubusercontent.com/assets/10283127/15050507/906c0abe-12f4-11e6-9d99-1697937d854c.png)

I'm not 100% sure on why this happens as the other layers that are called before the core validation layers also touch the debug callback, but I can reproduce this anytime with VS2015 and my examples on Windows 7 with a NVIDIA GTX 980 and current drivers.

Though I'm also not sure if it's really necessary that each of the layers actually checks the debug callback? If I'm not freeing it I get a validation message about the debug message callback not destroyed from each of the layers activated.

**Comment by courtney-g** [comment] 2016-05-05 17:37
Each layer maintains it's own list of callbacks so each layer must see all calls to vkCreateDebugReportCallbackEXT and vkDestroyDebugReportCallbackEXT.

The core validation code you are pointing at is just calling down the chain. I'd expect that. The actual destruction of the core validation's debug report callback happens on line 10275 in your example.

Is the fault happening at my_data->instance_dispatch_table->DestroyDebugReportCallbackEXT in the swapchain layer? If so, that could mean that the instance dispatch table probably didn't set the DestroyDebugReportCallbackEXT function pointer correctly.

**Comment by SaschaWillems** [comment] 2016-05-05 17:45
> Is the fault happening at my_data->instance_dispatch_table->DestroyDebugReportCallbackEXT in the swapchain layer? If so, that could mean that the instance dispatch table probably didn't set the DestroyDebugReportCallbackEXT function pointer correctly.

Yes, exactly :

![image](https://cloud.githubusercontent.com/assets/10283127/15051595/becf7ab2-12f9-11e6-9dcc-f2bdd7795193.png)

**Comment by ianelliottus** [comment] 2016-05-05 19:54
Hi @SaschaWillems.  I just tried to reproduce this with our demos/tests (with Courtney looking over my shoulder).  I tried a Linux box with an NVIDIA GPU, and a Windows laptop with an Intel GPU.  It's all working fine for me.  We thought of an experiment we'd like you to try:

Please run the LunarG cube demo (i.e. "cube --validate") and see if you see the same problem.

If you see the problem with cube, there's something about your system that's different than what we have, and we'll likely not be able to reproduce it (unless we get a different system:-).  If you don't see the problem with cube, please send me info on where to get your demos, how to build/run them, etc.

Thanks!
Ian

**Comment by SaschaWillems** [comment] 2016-05-05 20:20
I can reproduce this with the cube.c from the 1.0.11.0 SDK too. As a sidenote I was encountering this problem before and opened up an issue at the LunarXChange, but couldn't reproduce it again (and didn't check again until now).

The call stack looks a bit different though as for the cube.c demo it crashes inside debug_report.c :

![image](https://cloud.githubusercontent.com/assets/10283127/15055887/507bc99c-130f-11e6-9bc1-fae42a8ac9a8.png)

Call stack :

![image](https://cloud.githubusercontent.com/assets/10283127/15055901/5c61af60-130f-11e6-92c6-97bef8a137d5.png)

This may be specific to my setup though. I'll try to reproduce this on an AMD GPU tomorrow (after work) and report back if happens there too. If not, this may be a driver / GPU specific problem and not related to the validation layer itself.

**Comment by ianelliottus** [comment] 2016-05-05 20:46
Thanks for the info.  I'm looking forward to what you find with the AMD GPU tomorrow.

**Comment by MarkY-LunarG** [comment] 2016-05-05 20:50
I already fixed this today.  I encountered the issue on my Intel system.  I've committed the fix to master with commit # 999878744bdf08a860b9ee96ede44687eac636ab

**Comment by SaschaWillems** [comment] 2016-05-05 21:40
I build the layers from master, and the cube.c demo now runs fine. But my examples won't, I'm getting the exact same error. I'll do some further investigations into this tomorrow.

**Comment by SaschaWillems** [comment] 2016-05-07 12:37
Just checked with an AMD GPU and most recent drivers and the crash doesn't happen there too. Can this be caused by the driver? If so I'll setup a repo case for nvidia.

**Comment by ianelliottus** [comment] 2016-05-09 15:33
> Can this be caused by the driver?

Seems like a definite possibility.

**Comment by ianelliottus** [comment] 2016-05-17 18:07
Any news on this issue @SaschaWillems?

**Comment by SaschaWillems** [comment] 2016-05-18 11:00
@ianelliottus : Sorry, I haven't been able to dig deeper into thos on NVIDIA hardware yet, but as it won't happen other Vendors I'm pretty sure that it's related to the driver, so I guess it's safe to close this issue for now.

**Comment by ianelliottus** [comment] 2016-05-19 14:41
Thanks @SaschaWillems, I agree.  Please reopen this issue if it turns out to not be associated with the NVIDIA ICD/HW.  Am closing this now.

**Closed by ianelliottus** 2016-05-19 14:41 UTC
Labels: bug

**Comment by SaschaWillems** [comment] 2016-05-19 19:48
Thanks to Piers Daniell from NVIDIA I found the cause of this crash and why not everyone is able to reproduce this :

I mainly develop on an NVIDIA GPU but I sometimes switch it for an AMD GPU. As Windows is fine with this and loads up the drivers for the different GPUs just fine I don't remove drivers when switching from one vendor to another.

As such I have entries for the NVIDIA and AMD drivers in the registy :

![image](https://cloud.githubusercontent.com/assets/10283127/15407391/df29481c-1e0a-11e6-92b8-23c8015076f6.png)

And the crash I'm getting seems to be related to this.

Testing with NVIDIA I removed the AMD driver entry from the registry and the crash no longer happens.

Putting the AMD entry back in the crash occurs again.

If I switch to AMD while still having the NVIDIA driver entry in the registry I don't see the crash, so this may be tied to an alphabetical loading order?

So this seems to be a very specific issue not related to a special IHV at all, but rather only related to systems with multiple driver entries of which at least one is for a GPU currently not present.

I'm not sure how this should be handled, but (if it's possible to fix) it would be great if this won't would crash inside a validation layers. I can image that this may happen to more people in the future that switch to a different vendor without uninstalling drivers.

Should I open up a new issue for this or is it okay to continue here?

**Comment by courtney-g** [comment] 2016-05-19 20:25
That sounds like a potential loader bug. I'll assign this to Jon Ashburn to investigate.

**Comment by SaschaWillems** [comment] 2016-05-20 06:56
@courtney-g : Can you please reopen the issue then?

**Comment by courtney-g** [comment] 2016-05-20 13:28
Logged #569 to track this dual-card issue.
