### ISSUE TITLE
Link errors when trying to use functions from some extensions

### ISSUE THREAD

**Issue by haasn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2139] opened 2017-10-17 07:43 UTC
Some extensions, for example `VK_KHR_push_descriptor`, fail linking due to missing symbols such as `vkCmdPushDescriptorSetKHR`. This seems to me like an issue in the loader; since the generated `/usr/include/vulkan.h` defines these functions but the loader's `vulkan.so` doesn't export them. Another example, this one being quite a bit older, is `vkCreateDebugReportCallbackEXT`.

I would expect either:

1. The loader takes care of loading these functions in the same way that it takes care of loading everything else.
2. The generated vulkan.h omits functions it doesn't actually support and which users are intended to vkGetInstanceProcAddr themselves.

**Comment by jozefkucia** [comment] 2017-10-17 10:16
Vulkan loader doesn't export commands defined by extensions. You have to use `vkGetDeviceProcAddr()`.

The Vulkan specification says:
>However, commands defined by extensions may not be available for static linking - in
which case function pointers to these commands should be queried at runtime as described in
Command Function Pointers.

**Comment by haasn** [comment] 2017-10-17 10:26
Wait, then why does the vulkan loader export commands like `vkCreateXlibSurfaceKHR`? Aren't those also provided by extensions?

**Comment by jozefkucia** [comment] 2017-10-17 10:43
Yes, the desktop Vulkan loader exports some WSI extensions. It's documented here: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md#wsi-extensions. Instance extensions generally require support from loader so that's probably the main reason why WSI extensions are exported directly. Anyway, you can also load them using `vkGetInstanceProcAddr()`. Someone more knowledgable may have a better explanation.

**Comment by haasn** [comment] 2017-10-17 10:55
> Anyway, you can also load them using vkGetInstanceProcAddr(). Someone more knowledgable may have a better explanation.

I thought the whole point of the vulkan loader was to do away with the OpenGL scenario where everybody had to write their own custom loaders that loads every function under the sun into a dispatch table. And for the most part, it does - except for weird corner cases like this. Is it really expected that users develop their own vulkan loaders in every project? (Although I'm personally leaning towards just “not using push descriptors”)

**Comment by courtney-g** [comment] 2017-10-17 15:24
> Wait, then why does the vulkan loader export commands like vkCreateXlibSurfaceKHR? Aren't those also provided by extensions?

The Vulkan working group decided to export the WSI extensions because almost all apps would need to use those. Basically a convenience to the developer.

The loader was never intended to export all symbols. It doesn't know what they are and doesn't need to know. For example, for device extensions, the loader doesn't need to know about the extension functions to support the extension. All the loader needs to do is pass on the vkGetDeviceProcAddr to the driver and things work.

**Comment by mark-lunarg** [comment] 2017-10-17 16:59
Closing, as the loader is functioning as designed.

**Closed by mark-lunarg** 2017-10-17 16:59 UTC
