### ISSUE TITLE
 cmake fails to heed pkg-config include path 2

### ISSUE THREAD

**Issue by jengelh** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1989] opened 2017-08-07 18:58 UTC
Issue #1444 is back. Tried to build 1d0d15580070ae778c8a1f0c26cf023af8f5ef4a .
```
[   18s] [ 11%] Building C object loader/CMakeFiles/asm_offset.dir/asm_offset.c.o
[   18s] cd /home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/build/loader && /usr/bin/cc -DAPI_NAME=\"Vulkan\" -DFALLBACK_CONFIG_DIRS=\"/etc/xdg\" -DFALLBACK_DATA_DIRS=\"/usr/local/share:/usr/share\" -DSYSCONFDIR=\"/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/include -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/loader -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/build/loader -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/build  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -fvisibility=hidden -Wpointer-arith -O2 -g -DNDEBUG   -o CMakeFiles/asm_offset.dir/asm_offset.c.o   -c /home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/loader/asm_offset.c
[   18s] In file included from /home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/include/vulkan/vulkan.h:31:0,
[   18s]                  from /home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/loader/loader.h:31,
[   18s]                  from /home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/loader/asm_offset.c:24:
[   18s] /home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.54.0/include/vulkan/vk_platform.h:105:10: fatal error: wayland-client.h: No such file or directory
[   18s]  #include <wayland-client.h>
```

**Comment by johnzupin** [comment] 2017-08-08 18:12
Did PR #1461 ever fix your issue from before? It looks like that fix was removed in a latter commit some time ago probably by accident. 

I was unable to replicate the issue on Fedora but I currently don't have OpenSUSE system, assuming you're still using that OS.

Can you try this [patch](https://patch-diff.githubusercontent.com/raw/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1461.patch) from PR #1461 and let us know if it fixes your issue..

**Comment by jengelh** [comment] 2017-08-08 19:38
Yes, PR #1461 had fixed it. Commit 15c47bd3 (sdk 1.0.41 if I am not mistaken) builds without any additional modifications:
```
[   46s] cd /home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.41/build/layers && /usr/bin/c++  -DSYSCONFDIR=\"/etc\" -DVK_USE_PLATFORM_WAYLAND_KHR -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVkLayer_utils_EXPORTS -I/usr/include/wayland -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.41/include -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.41/layers -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.41/layers/../loader -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.41/layers/../include/vulkan -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.41/build/layers -I/home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.41/build  -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -std=c++11 -fno-rtti -fvisibility=hidden -Wpointer-arith -Wno-unused-function -Wno-sign-compare -O2 -g -DNDEBUG -fPIC   -o CMakeFiles/VkLayer_utils.dir/vk_layer_config.cpp.o -c /home/abuild/rpmbuild/BUILD/Vulkan-LoaderAndValidationLayers-1.0.41/layers/vk_layer_config.cpp
```
That was for a C++ file. asm_offset.c is a C file. Maybe that makes a difference with cmake?

**Comment by johnzupin** [comment] 2017-08-08 23:17
It looks like #1461 fix was removed at https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/7b06221f2c4cb2205e0363afe1ce59b81aa144a1#diff-af3b638bc2a3e6c650974192a53c7291. If that was your fix for OpenSUSE then we should pull that back in.

It looks like your issue #1444 is the same problem you're are having now that was fixed by #1461

**Comment by jengelh** [comment] 2017-08-08 23:38
I can confirm. Applying 8bf8992ececd9149e6ad6d70d52a4a90d6a87976 once again fixes the issue.

**Comment by johnzupin** [comment] 2017-08-21 22:43
I was able to reproduce this error on openSUSE. Created PR #2018 to reintroduce this fix.

**Comment by johnzupin** [comment] 2017-09-01 19:44
Merged the fix back in

**Closed by johnzupin** 2017-09-01 19:44 UTC
Labels: bug
