### ISSUE TITLE
Validation layers cause memory leak unless vkQueueWaitIdle is called every frame

### ISSUE THREAD

**Issue by LPGhatguy** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2468] opened 2018-03-07 00:15 UTC
I stumbled upon this running through the vulkan-tutorial.com introduction to Vulkan:

https://vulkan-tutorial.com/Drawing_a_triangle/Drawing/Rendering_and_presentation#page_Memory_leak

The full C++ source that should be able to trigger the leak [is here](https://vulkan-tutorial.com/code/15_hello_triangle.cpp).

You can work around the leak by turning the validation layers off, or by calling `vkQueueWaitIdle` after every `vkQueuePresentKHR` call. I observed this on my machine both with the pre-built source provided by vulkan-tutorial, as well as a dead-simple reimplementation in Rust.

On my machine, this issue appears to leak around 8 MB per second (!!)

**Comment by mark-lunarg** [comment] 2018-03-07 18:26
Thanks @LPGhatguy -- I'm thinking this is a duplicate of #1628, which is being tracked now in issue #1612, so I'll close this and track it there. Apparently, there's not a clean technical solution for this but we could probably detect the situation and keep the layers from crashing.

**Closed by mark-lunarg** 2018-03-07 18:26 UTC

**Comment by LPGhatguy** [comment] 2018-03-07 18:36
Awesome, thanks for helping me find that. I did a quick search over the issues but didn't find any terms that matched what I knew about the leak so far.

**Comment by mark-lunarg** [comment] 2018-03-07 18:48
Thank you -- we very much appreciate your contributions!
