### ISSUE TITLE
Cross-queue memory barriers not validated properly

### ISSUE THREAD

**Issue by phaulos** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1550] opened 2017-03-09 22:42 UTC
Seems that validation layers have some limitations in validating cross-queue barriers. For example `dEQP-VK.synchronization.op.multi_queue.fence.write_update_buffer_read_ubo_vertex.buffer_16384_exclusive` is failing with:

```
ERROR: vkCmdPipelineBarrier(): dstStageMask flag VK_PIPELINE_STAGE_VERTEX_SHADER_BIT is not compatible with the queue family properties of this command buffer. For more information refer to Vulkan Spec Section '6.5. Pipeline Barriers' which states 'Any pipeline stage included in srcStageMask or dstStageMask must be supported by the capabilities of the queue family specified by the queueFamilyIndex member of the VkCommandPoolCreateInfo structure that was used to create the VkCommandPool that commandBuffer was allocated from, as specified in the table of supported pipeline stages.' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#VkDependencyFlagBits) (code 0x000009d1 from DL at CommandBuffer:8286)
```

This command is targeted at command buffer for queue index 1 which is transfer-only queue (and thus doesn't support VK_PIPELINE_STAGE_VERTEX_SHADER_BIT). However `VkBufferMemoryBarrier::dstQueueFamilyIndex` points to queue index 0 which is graphics-capable queue. Seems that `dstStageMask` is incorrectly checked against queue associated with the command buffer, not the `dstQueueFamilyIndex`.

**Comment by krOoze** [comment] 2017-11-26 17:22
Actually `dstStageMask` or `srcStageMask` should be completely ignored on transfer barriers.
I think this is esentially another duplicate of #865 and #1986.

**Comment by jzulauf-lunarg** [comment] 2018-03-30 14:45
Should be fixed by 2521 above.

**Closed by jzulauf-lunarg** 2018-03-30 14:45 UTC
Labels: bug
