### ISSUE TITLE
Enabling VK_EXT_debug_marker w/validation layers active & no other implementation leads to crash

### ISSUE THREAD

**Issue by cdwfs** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2314] opened 2018-01-04 00:32 UTC
**Repro:**

1. Enable the standard_validation layer at instance creation time
2. Enable `VK_EXT_debug_marker` at device creation time.
3. Load a pointer to `vkCmdDebugMarkerBeginEXT` with `vkGetDeviceProcAddr`, and use it to insert a command buffer marker. Guard the call by ensuring that the extension is active, that `vkGetDeviceProcAddr` returned a non-NULL function pointer, etc.; it won't help 😈 
4. Run the application in a context where the only implementation of `VK_EXT_debug_marker` is the one exposed by the validation layers (i.e. without a RenderDoc or RGP capture active). (NOTE: this used to trigger a loader warning until it was downgraded to a debug message this morning by a5ced439)

**Expected result:** The call to `vkCmdDebugMarkerBeginEXT` should be a no-op, if no device-specific implementation is available.
**Actual result:** A crash due to a NULL pointer dereference in the object_tracker layer, which isn't checking whether the next layer down in the dispatch table is NULL before calling it. Note that it is difficult (if not impossible) to tell whether it's safe to call `VK_EXT_debug_marker` functions; the extension may load correctly (from the layers), the functions may load correctly (also from the layers), but they'll still crash if you call them.

The layers seem to routinely assume the dispatch table function pointers are non-NULL before calling them, so I assume they expect each dispatch chain to be terminated with a stub function if the next layer down doesn't provide an implementation. Could the debug_marker functions be missing their terminators?

**Comment by lenny-lunarg** [comment] 2018-01-04 18:56
We've been able to reproduce this crash and there's definitely a problem that should be fixed here, but we've been debating internally how we want to fix this. The basic problem is that the loader sees that the layers implement `VK_EXT_debug_marker` and it lets the application enable it. The loader expects that the layer that implements each function won't call further down the chain. However, the extension really isn't implemented by one layer &mdash; it's implemented by several of them. As a result, the layers need to call down, and this causes the crash.

We have a couple of ways that we can solve this, but I think we're going to take a little longer to figure out which method seems best to us, because they all have drawbacks.

**Comment by cdwfs** [comment] 2018-01-04 19:28
Glad to hear it's on the radar at least :)

BTW I was just able to trigger the same crash during a RenderDoc capture; according to the call stack, the renderdoc.dll implicit layer appears earlier in the dispatch chain than the validation layers, so the layers still hit that NULL pointer at the end of the chain.

**Comment by cdwfs** [comment] 2018-03-12 18:23
On closer inspection this looks like it may be a duplicate of #1074.

**Closed** 2018-05-04 18:16 UTC
Labels: bug, duplicate
