### ISSUE TITLE
Memory Layer complaining about invalid memory being read by vkCmdCopyImageToBuffer(), even though it is correctly filled earlier.

### ISSUE THREAD

**Issue by KarenGhavam** [KhronosGroup/Vulkan-LoaderAndValidationLayers#67] opened 2016-03-03 20:15 UTC
This issue came from LunarXchange (issue number 303).

Consider the following command buffers:

Command Buffer 1: Blit image A to image B, possibly performing format conversion along the way. Command Buffer 2: Copy whole image B's contents to buffer X with a vkCmdCopyImageToBuffer() call.

Now, let's build a single submission consisting of the two command buffers. Let Command Buffer 1 signal a semaphore, that Command Buffer 2 waits upon before starting execution.

Once the command buffers finish executing, we try to map the buffer X's memory buffer into process space and read from it.

With this chain of action, I'm getting a call-back from the Memory layer, telling that "VkCmdCopyImageToBuffer(): Cannot read invalid memory <image B's memory buffer>, please fill the memory before using.", which I believe is incorrect.

**Comment by lentinem** [comment] 2016-03-03 22:32
What order are the command buffers being executed in? The spec requires 1 is submitted before 2 and this could trigger if thats not the case (section 5.5).

**Comment by lentinem** [comment] 2016-03-03 22:33
Jon; I'm not sure how to find out more from the original submitter. Can you ask them for more info on the ordering and if possible a repro?

**Comment by KarenGhavam** [comment] 2016-03-03 23:40
The original submitter was Dominik Witczak. I have sent him email to come to this issue and answer your questions.

**Comment by KarenGhavam** [comment] 2016-03-03 23:51
Michael,

Dominick Witczak was original submitter. I will ask him to begin watching
the Github issue and to answer your question.

Karen Ghavam
CEO
LunarG, Inc. - 3D Graphics Software Innovations
karen@lunarg.com
970-988-9043

**Comment by kbiElude** [comment] 2016-03-04 08:46
I'll need to re-check this, this issue has been reported months ago so I can't tell whether the problem still reproduces.

**Comment by jon-lunarg** [comment] 2016-03-04 15:15
Dominik:

Maybe I don't understand your case,  But  it seems if both command buffers  are in the same QueueSubmit, then  a semaphore can't be used to synchronize between command buffer 1 and command buffer 2 access to image B.  How about using a memory barrier for synchronize access to image B?

**Comment by lentinem** [comment] 2016-03-09 19:03
Assigning to Karen as we need a repro for this but I'm not sure Dominik's user id and Karen created it.

**Comment by kbiElude** [comment] 2016-03-09 19:06
Apologies, I've just gotten back from a short vacation today and been busy with other stuff since the very morning. I'm really hoping to be able to move on to validation layers tomorrow. Fingers crossed!

**Comment by kbiElude** [comment] 2016-03-10 09:07
OK, this issue continues to reproduce with HEAD version of the repo, so let me elaborate on how it can be reproduced.

1. Consider command buffers A and B as originally described. The command buffers are not synchronized with events - this is not necessary..
2. ..because the synchronization is handled by configuring the VkSubmitInfo descriptors accordingly. These are lated passed to a single vkQueueSubmit() invocation. In specific:

* setting command buffer A's VkSubmitInfo::pSignalSemaphore to semaphoreA and setting VkSubmitInfo::signalSemaphoreCount to 1.
* setting command buffer B's VkSubmitInfo::pWaitSemaphores to semaphoreA and setting VkSubmitInfo::waitSemaphoreCount to 1.

The call-back occurs at vkQueueSubmit() call time, and the call-stack is as below:

![image](https://cloud.githubusercontent.com/assets/9154207/13664497/e8a341e4-e6a7-11e5-8221-4a8fefc3bd9a.png)

**Comment by lentinem** [comment] 2016-03-10 15:45
I had tried to repro this before without success. I would like to clarify that while you can submit both at the same time; 1 must appear before 2 (or A before B) in the list (forward progress) or errors like this can occur. If you are doing this it is likely a bug but unless someone can repro it will be hard to track.

**Comment by DominikWitczakAMD** [comment] 2016-03-11 09:21
Yeah, the command buffers are submitted in the right order. I'll try having a stab at this.

**Comment by DominikWitczakAMD** [comment] 2016-03-11 09:39
OK, nailed this down. Will propose a pull request in a sec.

**Comment by DominikWitczakAMD** [comment] 2016-03-30 10:45
I think it's OK to close this, since the error no longer reproduces.

**Closed by DominikWitczakAMD** 2016-03-30 10:45 UTC
Labels: question
