### ISSUE TITLE
Core validation layer incorrectly reports that swapchain image memory has not been filled.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#676] opened 2016-06-21 19:40 UTC
When using compute only to update a swapchain image you get:

    vkQueuePresentKHR(): Cannot read invalid swapchain image 0x5, please fill the memory before using.

I thought this issue had been reported before but I can't find the issue.

**Comment by mark-lunarg** [comment] 2016-06-23 20:20
Johannes -- Was the image updated using CmdDispatch[Indirect]?  It looks like the validation for this is wired up correctly including some fixes in the past month or so.  Are you on Master, or using one of the SDKs?

**Comment by mre4ce** [comment] 2016-06-23 21:49
I was using latest master. The compute work is submitted with vkCmdDispatch.

I thought we fixed this issue already so I was surprised to see it show up again. The original issue was filed on GitLab issue #90.

**Comment by mark-lunarg** [comment] 2016-06-23 22:09
There've been a lot of descriptor-set changes lately, is this a regression?  Is there any way we can get a repro case, or some straightforward instructions on creating one?

**Comment by mre4ce** [comment] 2016-06-23 23:04
The https://github.com/KhronosGroup/Vulkan-Samples/blob/master/samples/apps/atw/atw_vulkan.c sample runs into this issue.

**Comment by mre4ce** [comment] 2016-06-24 00:29
I've tried the latest 1.0.17.0 SDK and I've tried latest main as well and I can't reproduce the issue. Could there be a threading issue making this a rare occurrence?

**Comment by mark-lunarg** [comment] 2016-06-24 18:20
Johannes --  though it is possible it seems unlikely.  I have fiddled with atw this morning and I can't get it to reproduce either.  If you see it again we can reopen this issue but for now I'm going to close it and move onto some other ones.  Thanks.

**Closed by mark-lunarg** 2016-06-24 18:20 UTC
Labels: bug

**Comment by mre4ce** [comment] 2016-06-25 17:02
Agreed. I'll let you know if it happens again and I'll make sure I have a good repro case. Thanks!
