### ISSUE TITLE
The core validation layer incorrectly states that layouts are not compatible.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/Vulkan-LoaderAndValidationLayers#450] opened 2016-04-29 02:51 UTC
With latest master I'm getting:

    Error: [DS] Code 42 : descriptorSet #0 being bound is not compatible with overlapping layout in pipelineLayout due to: Binding 0 for DescriptorSetLayout 00000000000001C0 has a descriptorCount of 1 but binding 0 for DescriptorSetLayout 00000000000001BC has a descriptorCount of 4

Note that the actual pipeline layout passed into vkCmdBindDescriptorSets is 00000000000001C1 not 00000000000001C0.

**Comment by tobine** [comment] 2016-04-29 13:25
I don't suppose you have a simple repo case?

Note that this check is based on the following valid usage language for vkCmdBindDescriptorSets:

`Any given element of pDescriptorSets must have been created with a VkDescriptorSetLayout that matches (is the same as, or defined identically to) the VkDescriptorSetLayout at set n in layout, where n is the sum of firstSet and the index into pDescriptorSets`

So DescriptorSetLayout 0x1C0 is a VkDescriptorSetLayout object that is at index "0+firstSet" of the vkPipelineLayout (0x1C0?) that was passed into vkCmdBindDescriptorSets.

I don't doubt that there may be a bug here, but just need more info.

**Comment by tobine** [comment] 2016-04-29 13:42
Filed #453 to clarify the error message here so distinction between VkPipelineLayout and VkDescriptorSetLayout within that VkPipelineLayout is clearer. That's not intended to fix anything, just help users and myself for debugging going fwd.

**Comment by mre4ce** [comment] 2016-04-29 15:36
I can send you an exe that reproduces the problem.

I'm switching between two pipelines that use the exact same descriptor set layout, but each their own VkDescriptorSetLayout and VkPipelineLayout. I'm then rendering the second pipeline with a VkDescriptorSet created using the VkDescriptorSetLayout from the first pipeline.

**Comment by tobine** [comment] 2016-04-29 17:21
Sadly I don't have a setup to windows debugging.

Your update is confusing me. Can you send me a brief write-up for clarification?
Which VkDescriptorSetLayouts are each VkPipelineLayout referencing and which of those VkDescriptorSetLayouts has 1 descriptor & which has 4 descriptors?
Which VkPipelineLayout is each pipeline referencing?

I've just pushed my update to clarify this error message a bit. Can you re-run with latest master and send me the updated error message?

**Comment by mre4ce** [comment] 2016-04-29 20:58
There are two pipelines. Each has its own VkDescriptorSetLayout and VkPipelineLayout. However, the descriptor set layouts are the same. Both use 4 descriptors. The VkDescriptorSetLayout with 1 descriptor is unrelated and not used.

I call vkCmdBindDescriptorSets with the VkPipelineLayout from the second pipeline and a VkDescriptorSet created using the VkDescriptorSetLayout from the first pipeline.

**Comment by mre4ce** [comment] 2016-04-29 21:41
Using latest master the message is:

Error: [DS] Code 42 : descriptorSet #0 being bound is not compatible with overlapping descriptorSetLayout at index 0 of pipelineLayout 0x42 due to: Binding 0 for DescriptorSetLayout 0000000000000041 has a descriptorCount of 1 but binding 0 for DescriptorSetLayout 000000000000003D has a descriptorCount of 4

**Comment by dustin-lunarg** [comment] 2016-04-29 23:41
@mre4ce, if you want to send me the exe that reproduces the problem, I can try debugging it.  You can try uploading the .exe to an issue you create on LunarXChange if you have an account there.  If there are issues sharing the .exe publicly, we can set it up so you can submit it privately through LunarXChange.

**Comment by mre4ce** [comment] 2016-04-30 02:56
I've attached an executable to issue #507 on LunarXChange. You have to hit the [E] key twice to hit the validation error.

**Comment by tobine** [comment] 2016-05-02 18:35
Note that I pushed a fix today for #463 which could be related. That error was different but there was definitely a bug in layout compatibility checks that is now fixed and could affect this case.

**Comment by dustin-lunarg** [comment] 2016-05-02 20:25
It looks like PR #466, submitted to fix issue #463, has also fixed this problem.  When running the provided executable with the tip-of-tree source, I do not see any errors.  If I roll back to commit 3df71a7, just before #466, I am seeing the errors as reported.

**Comment by jon-lunarg** [comment] 2016-05-03 17:55
Looks like this can be closed.

**Closed by jon-lunarg** 2016-05-03 17:55 UTC
Labels: help wanted

**Comment by mre4ce** [comment] 2016-05-03 18:52
I tested with latest master as well and the problem is fixed. Thanks!
