### ISSUE TITLE
Core_validation: ValidateCmdBufImageLayouts() should be treating D views of DS images as DS image views

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#650] opened 2016-06-16 12:38 UTC
There's a pretty peculiar boundary case in the spec which seems to be not respected by the core validation layer in all situations.

When describing the image view creation process, the spec mentions that:

> When an imageView of a depth/stencil image is used as a depth/stencil framebuffer attachment, the aspectMask is ignored and both depth and stencil image subresources are used.

Now, consider the following scenario:

1. Image X is a DS image.
2. Image view Y is a depth-only image view created from image X.
3. We create a framebuffer Z, whose one of the attachments point is image view Y. Let's say it's an attachment W.
4. Then, we form a renderpass consisting of two subpasses (0 and 1) which uses framebuffer Z. On the renderpass level, attachment W uses a GENERAL initial & final layout. On the subpass level, it is used by subpass 0, where it acts as a target for rasterized DS data. Again, GENERAL layout is used for that subpass.
5. At the beginning of subpass 1, an image barrier is recorded which transitions image X from GENERAL to SHADER_READ_ONLY_OPTIMAL. The subresource range's aspect has both DEPTH_BIT and STENCIL_BIT set. Later on, the image is sampled from from within a draw call invocation.

At vkQueueSubmit() time, I'm being reported about the following problem:

![image](https://cloud.githubusercontent.com/assets/17761066/16116505/9be693a6-33cd-11e6-8b08-c7480c52be8d.png)

0x4 corresponds to STENCIL_BIT. 

Since the barrier uses an aspectMask of 0x6, that error is incorrect.

**Comment by tobine** [comment] 2016-07-07 19:33
@DominikWitczakAMD I can certainly believe that validation may not correctly be handling this case, but after an examination of the code and walking through the situation you outline I don't see a clear bug.

Do you have a test case that reproduces this?

The image memory barrier in step 5 of your example will go through TransitionImageLayouts() function of core_validation. That function will call SetLayout() which iterates over each aspect bit. This should effectively transition both the D & S aspects of the image to SHADER_READ_ONLY_OPTIMAL. This should have the same result as "ignoring the aspectMask" as you point out from the spec. If that was happening, though, you wouldn't see the error you're reporting so I'm missing something that should easily come to light with a repo case.

**Comment by DominikWitczakAMD** [comment] 2016-07-08 11:47
We do in fact :-) Let's take this off-line

**Comment by tobine** [comment] 2016-07-11 22:40
@DominikWitczakAMD please send the repro case to @mark-lunarg 
LunarG has access to Windows AMD box that should speed resolution of this issue.

**Comment by DominikWitczakAMD** [comment] 2016-07-12 06:32
Done

**Comment by mark-lunarg** [comment] 2016-07-13 17:07
@DominikWitczakAMD , we've reproduced it here and have a handle on the cause.  Tony is putting together a simple test case we can share with @tobine to get this resolved.

**Comment by DominikWitczakAMD** [comment] 2016-07-13 17:12
:sunglasses:

**Comment by tobine** [comment] 2016-07-13 17:24
@mark-lunarg @Tony-LunarG nice!

**Comment by tobine** [comment] 2016-07-19 23:25
Alright, I've looked at this further. The example test was producing a failure somewhat similar to the failure seen by @DominikWitczakAMD, but I believe that the cause was a test framework bug. In the simple test case, the initial layout for the DS image was being set with the COLOR aspect bit, which is illegal and was appropriately being flagged by validation.

@Tony-LunarG please see my branch "tobin_gh650_image_aspect_validation" which has a couple of CLs added to your previous test branch. The first CL fixes the test framework to correctly set aspect bit on image transitions. This eliminates the layout transition error in the test. The second CL updates the simple test to call VerifyNotFound() when complete so that any errors will be flagged. Note that there are a couple of unrelated errors still being flagged.

@mark-lunarg and @Tony-LunarG can you give this another look? If the real case is setting an image transition on a DS image with the COLOR aspect bit, that would be the issue, but I suspect that's not the case.

**Comment by tobine** [comment] 2016-08-04 01:45
Fixed by #810 
Fix was cherry-picked and pushed to master

**Comment by tobine** [comment] 2016-08-04 02:38
Fix was causing some false positives to re-opening.

**Comment by mark-lunarg** [comment] 2016-08-05 16:13
Pushed fix to Master.
commit 038f931c1696f3e96aeec0e3786b5a47acf908e1
Author: Mark Lobodzinski <mark@lunarg.com>
Date:   Fri Aug 5 09:38:18 2016 -0600

    layers: Reenable fix for DS layout transitions

    Fix for GH650, plus added fix for cube/tri.

    Change-Id: I66c2332c30eb34a0f022c033efd9b1c5b8284c32

**Closed by mark-lunarg** 2016-08-05 16:13 UTC
Labels: bug
