### ISSUE TITLE
Exposing extension entry points from loader?

### ISSUE THREAD

**Issue by nsubtil** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2143] opened 2017-10-17 23:33 UTC
During a conversation at the Chicago F2F, the issue of extension loading in Vulkan came up. @mtavenrath has extensive experience with this particular topic and has found a few ways in which this is a thorny problem for Vulkan applications:

* It is illegal to define any app-side symbols that start with the string 'vk'. This means one can not define extension entry point symbols by name in client code. This causes a problem for libraries such as vulkan.hpp and creates friction between various modules (e.g., middleware) that may interact with a single Vulkan context.
* Function pointers obtained from one instance are not valid across instances. Similarly, function pointers obtained on one device are not valid on another. Function pointers obtained for the same physical device on different logical devices are not interchangeable either.

This makes implementing extension loading correctly somewhat tricky. Apps effectively have to set up separate pointer tables for instance vs. device extensions and associate them with specific VkInstance / VkDevice objects, which leads to messy app-side code (and a very different way of calling into core vs. extension entrypoints). The trampoline code required to deal with this situation is also likely to become sub-optimal depending on how many of the requirements a given implementation decides to respect.

It would be desirable to let the loader handle this directly, by exposing all registered extension entry points and reusing the same internal trampoline code that is in place for the core API (which already deals with the same set of restrictions). This would reduce the surface area for app-side errors that manifest themselves only in less common systems (and end up requiring ugly IHV workarounds), besides potentially reducing function call overhead for extension entrypoints (compared to homegrown solutions per app) and overall making Vulkan more usable.

The conversation at the F2F (mostly between Piers Daniell, Jesse Hall, Jason Ekstrand, Markus Tavenrath and myself) seemed to indicate this would be doable. There is a caveat with apps that expect symbols to be present in the loader where an end-user system might have an older loader without those symbols, which could lead to a cryptic OS message when attempting to run the app. There seem to be several possible solutions to this problem:

* Enable delay-loading at link time for the Vulkan loader and check the loader version before making any extension calls. If the version is too low, warn the user and exit. (This is possible today on Windows by checking the DLL version field, though an explicit API could be added for this.)
* Enable delay-loading, add hooks to catch symbol loading errors, warn the user and exit if an error occurs.
* Ship an installer for the loader as part of the prerequisites for the app, which updates the loader if the system-installed version is too old. There is precedent for this on Windows platforms, MSVC runtime installers being a very common example (and platforms like Steam handle such things automatically for games).
* Check the system loader version during installation and abort if it is too old. (Linux platforms tend to have this sort of dependency version checking built in.)

I'd like to open this idea up for discussion. Would it be viable to expose registered extension entry points from the loader?

**Comment by polarina** [comment] 2017-10-18 01:19
> [...] Similarly, function pointers obtained on one device are not valid on another. Function pointers obtained for the same physical device on different logical devices are not interchangeable either.

Apps can use `vkGetInstanceProcAddr` to obtain function pointers that are usable with all VkDevices created from the same instance.

**Comment by courtney-g** [comment] 2017-10-18 16:43
Goals during loader development (see mcjohn@valvesoftware.com for more details):

- Eliminate cryptic application startup errors due to missing symbols
  Valve felt quite strongly on this, but is an attractive feature in that application will be able to start and warn user if system is missing necessary extensions instead of dying in linker.
- Optimal path to Vulkan functions
  Using vkGetDeviceProcAddr will give you function pointer to driver function. Fastest way to get to the driver. Is specific to VkDevice. As mentioned by @polarina, can use vkGetInstanceProcAddr if you want more generic function pointer. Though the difference isn't that large, this was a very attractive feature to lots of folks in the working group.
- Support layer architecture with minimal impact to perf
  Allow use of API validation during development that is gone / has no impact on application running in production.
- Support multiple independent "users" within a process
  For example, some library the application uses could use Vulkan with it's own VkInstance with it's own extensions and layers that would be completely independent of the application.
- Allow for multiple ICDs without interfering with each other
  Fix / avoid issues Linux sees with OpenGL.
- Explicitly declare extensions used / needed by application
  Prevent hidden / unintended use of extensions. This helps eliminates failure mode where application is run on a different device than where it was developed and is trying to use extensions not supported on this device.

**Comment by lenny-lunarg** [comment] 2017-10-18 18:14
To provide a historical perspective on why the loader was designed to not export extension symbols, let me provide the list of reasons. If the loader had been designed to export extension symbols, the application would have to deal with all of the following:


- Any application that uses an extension entrypoint would need to make sure that it is linking with a loader that supports the extension.
  - If linking with an older loader, the application will fail with OS-level errors.
  - This implies a tighter binding between the application header version and the loader version.
  - In the current design, it is possible for an application to run on a system with older versions of the loader.
- Extensions were expected to be added and then possibly removed from the API on a regular basis.
  - This would mean that newer loaders could cause OS-level errors with older applications for extensions that were removed.
- Exporting extension entrypoints would make it easier for applications to call into unsupported extensions because the
application does not have to fetch the function pointer from vkGet*ProcAddr.

These suggested workarounds in this issue could allow the symbols to be exported, however, they represent a paradigm shift because they would change how the loader is delivered and utilized in the ecosystem. This would require buy-in from ISVs and IHVs

- Exporting the symbols from the loader forces the application to coordinate the header version with the loader more closely.
- If the task of verifying that entrypoints are present is handled by the application, then extra OS-specific code will be required to handle this task and would likely turn out to be more work for the application than simply loading the symbols through Vulkan's platform-independent mechanisms.
- This work could be offloaded into some other utility, but creating a loader that loads the Vulkan loader seems like a roundabout solution that violates Vulkan's aim of reducing abstractions.

**Comment by cubanismo** [comment] 2017-10-18 18:36
Yeah, please don't have the loader export all extension symbols.  This:

> If linking with an older loader, the application will fail with OS-level errors.

caused us so much trouble with GL on Linux we ended up back-tracking from exporting all symbols and instead defining a de-facto ABI when we finally got a unified loader on Linux (GLVND).  If that experience and the general quality of bug reports we've gotten from Vulkan developers has taught me anything, it's that if developers can do less work, they will.  They won't test on old loaders/drivers/etc., they won't be aware of or heed advice to use lazy-resolve linking if some other option is available and just works on their favorite test system, and they definitely won't use vkGet*ProcAddress anymore, and won't have much sympathy for Khronos/the Vulkan ecosystem maintainers pointing at short paragraphs in our 1000+ pages of spec/appendices/guidance/blogs/notes when their app ends up being crashy.  No one seems to have the time or incentive to think about stuff that isn't actively blocking their progress.

The problems listed above with the current situation don't seem that big to me.  Trampoline layers that try to seem invisible to the app aren't a good path to pursue IMHO.  That wasn't a great idea in GL, and it isn't a great idea in Vulkan.  However, each app shouldn't have to write code to build per-instance+device function tables, but that's what the "trampoline" helper should do: something very slightly higher level.  Yeah, it gets tricky with middleware, but "tricky" is better than everything mysteriously failing to load all the time.

**Comment by mark-lunarg** [comment] 2017-10-20 19:48
@nsubtil, @mtavenrath, unless and until we hear otherwise from the working group, there doesn't appear to be any related work targeted for this particular repo so we'll close this issue for now. If a utility were to be developed, it's entirely possible it could be included in the SDK just as vulkan.hpp is.  Good luck!

**Closed by mark-lunarg** 2017-10-20 19:48 UTC

**Comment by KarenGhavam-lunarG** [comment] 2017-10-20 22:34
Nuno,

You posted to the Vulkan WG:

> While we’re trying to get the ecosystem group set up, I wanted to see if we could start an open discussion on a couple of issues, so I filed a github issue for one of them. The topic in question is whether we can / should start exposing registered extension entry points from the loader.

It was good that you posted the issue on github. You got reviews and feedback from Vulkan WG members as well as more detailed information from the architects and implementers of the Vulkan loader. 
 

> Given that it was closed on short order with the message below, it sounds like this is not the right venue after all. I wanted to get the WG’s input on whether there is a venue that we might be able to use for this particular conversation in the meantime.

I am not sure it was closed on short order. I do think posting to github for the original issue was the correct discussion venue. From the feedback to the original post, it didn't appear that exposing extensions from the loader was the correct path forward and the original request to modify the loader was no longer open. Hence why it was closed.

Markus' post is talking about another possible solution to create a utility. If such a utility were to be created, it wasn't believed it would be part of the loader and validation layers repo (perhaps it was prematurely assumed this would be a utility that is included with Vulkan-HPP).
