### ISSUE TITLE
Validation layers doesn't check for NULL when provided count is greater then 0

### ISSUE THREAD

**Issue by RippeR37** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1685] opened 2017-04-22 18:59 UTC
Many Vulkan commands and structures takes some arguments in pairs: count and pointer to an array.
I've noticed however, that validation layers doesn't check if pointer is not NULL if count is greater then 0.

For some fields, pointers can be set to NULL, so it can't be simply checking all `pSomethingSomething` for NULLs. However such checks might be useful as sometimes something is added over a time and some fields might not have been updated with others which might lead to crash or god knows what...

One of such places is `VkPipelineViewportStateCreateInfo` structure which has pairs:
* `viewportCount` and `pViewports`
* `scissorCount` and `pScissors`

On my system (Windows 7 x64, Nvidia GTX 660M, latest drivers) it lead to crash on `vkCreateGraphicsPipelines`. Usually it will be easy to find, but in such big struct like the ones for pipelines it might take some time...

**Comment by jeremy-lunarg** [comment] 2017-04-28 16:48
> On my system (Windows 7 x64, Nvidia GTX 660M, latest drivers) it lead to crash on `vkCreateGraphicsPipelines`.

Can you double check that the parameter_validation layer is loaded? If the corresponding state is not dynamic, it should validate the `pViewports` and `pScissors` pointers during `vkCreateGraphicsPipelines`. We have tests for these errors in `layer_validation_tests.cpp` (`VALIDATION_ERROR_02110` and `VALIDATION_ERROR_02111`).

**Comment by krOoze** [comment] 2017-04-29 17:36
Your specific count&ndash;array pair example is one of the more complicated ones. (The spec VU has to be hand-made for this case and the relation is further complicated by other variables.)

But for other arrays I think the  KhronosGroup/Vulkan-Docs#491 . (The count > 0 + nullptr seem to be currently allowed &mdash; but maybe it shouldn't be)

**Comment by jeremy-lunarg** [comment] 2017-05-01 21:36
With respect to `pViewports` and `pScissors`, a `nullptr` can make it through the validation layers and into the driver if the state is dynamic, the count is between `1` and `VkPhysicalDeviceLimits::max*` inclusive, and the pointer is null. In which case, I believe the driver should ignore the pointer as stated in the spec.

The issue raised by @krOoze is relevant and may affect the VUs.

**Comment by RippeR37** [comment] 2017-05-31 10:56
@jeremy-lunarg I was using standard LunarG meta-layer in 1.0.42.2 VulkanSDK so I assume it is.
I didn't use any dynamic state there, it was simple demo.

Maybe at least warn if `*Count` is bigger then 0 and pointer to array is `nullptr`? If indeed standard is allows such usage, maybe it really is a drivers fault. Though I don't think that using it that makes any sense, so warning might be a good option?

**Comment by karl-lunarg** [comment] 2017-11-14 02:02
There's no VU for the pointers having to be non-NULL.  As mentioned above, if the state is dynamic, then the pointers should never be dereferenced by the driver.  However, if the state is not dynamic, then the pointers have to implicitly be non-NULL since the counts have to be at least 1.

There is a check for a null viewports pointer in the `pv_vkCreateGraphicsPipelines` function in `layers/parameter_validation_utils.cpp`, where `VALIDATION_ERROR_096005d6` is reported.  As @jeremy-lunarg pointed, out there is also a test in the layer test suite called `PSOViewportCountWithoutDataAndDynScissorMismatch`.

@RippeR37, this seems to be working as designed.  Can you try again by setting the pointer back to NULL and see if you get the validation error?

**Comment by krOoze** [comment] 2017-11-14 22:45
@karl-lunarg I do not get a error message with latest SDK, nor with master.

**Comment by karl-lunarg** [comment] 2017-11-14 23:33
Yep. that's the problem.  I hacked cube.c to have the viewport and scissors not be dynamic and set pViewports to NULL.  But I left the dynamic state struct in place with all the enable flags turned off and I got the validation message before the crash in the driver.  But if I set pDynamicState to NULL, I get the crash with no validation message.

The VL test suite has scissors being dynamic when trying a NULL viewport and vice-versa.  So, it never caught this problem because there was always a dynamic state struct provided.

**Comment by krOoze** [comment] 2017-11-14 23:40
@karl-lunarg PR comming up soon.

**Comment by karl-lunarg** [comment] 2017-11-14 23:59
Cool!  I have a fix as well and we'll see if it is the same as yours :-). 

Are you going to add a test?  I ask because I think that PSOViewportCountWithoutDataAndDynScissorMismatch and PSOScissorCountWithoutDataAndDynViewportMismatch could use some refactoring.  Both tests are skipped if multiple viewports are not supported.  They each test the NULL pointer case and the dynamicCount != PSOcount case.  It seems that the NULL pointer case should still be tested even if multiple viewports are not supported.  Anyway, we'll wait for your PR and discuss this there or make another issue/PR to do the refactoring I'm talking about.

**Comment by krOoze** [comment] 2017-11-15 00:06
> Are you going to add a test?
@karl-lunarg Of course. TBH, I am opportunistically cleaning the layer code a bit too.

**Comment by krOoze** [comment] 2017-11-16 12:36
@RippeR37 #2209 should fix your specific example

**Comment by krOoze** [comment] 2017-11-26 17:18
@mark-lunarg I think this can be closed. AIS automatic parameter_validator should handle this, and the specific non-automatic validation of the specific example was fixed. If there is some other example it can be made into a new Issue...

**Comment by mark-lunarg** [comment] 2017-11-27 16:48
Closing then.  Thanks a bunch @krOoze.

**Closed by mark-lunarg** 2017-11-27 16:48 UTC
Labels: incomplete
