### ISSUE TITLE
OBJTRACK, THREADING : DestroyCommandPool null pointer

### ISSUE THREAD

**Issue by ArkadiuszSarwa** [KhronosGroup/Vulkan-LoaderAndValidationLayers#719] opened 2016-07-01 11:34 UTC
I'm getting error messages form layers when I run the graphic pipeline on many threads.
I have only one graphic queue available, and I use synchronization on host to protected using this same queue on many threads,
commmandPool and commandBuffer are created on stack of function executed on thread.

Errors: 

> THREADING(ERROR): object: 0x612e020 type: 6 location: 0 msgCode: 1: THREADING ERROR : object of type VkCommandBuffer is simultaneously used in thread 6472 and thread 6424
> OBJTRACK(ERROR): object: 0x612e020 type: 6 location: 1319 msgCode: 4: Invalid VkCommandBuffer Object 0x612e020    \

There is no possibility that this same commnadBuffer is used on other thread. 
When objects are later destroyed, I'm getting a null pointer and a crash in file "object_tracker.h" 

```
void explicit_DestroyCommandPool(VkDevice device, VkCommandPool commandPool, const VkAllocationCallbacks *pAllocator) {
    bool skipCall = false;
    std::unique_lock<std::mutex> lock(global_lock);
    skipCall |= validate_device(device, device, VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT, false);
    skipCall |= validate_command_pool(device, commandPool, VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_POOL_EXT, false);
    lock.unlock();
    if (skipCall) {
        return;
    }
    lock.lock();
    // A CommandPool's command buffers are implicitly deleted when the pool is deleted.
    // Remove this pool's cmdBuffers from our cmd buffer map.
    std::unordered_map<uint64_t, OBJTRACK_NODE *>::iterator itr = VkCommandBufferMap.begin();
    std::unordered_map<uint64_t, OBJTRACK_NODE *>::iterator del_itr;
    while (itr != VkCommandBufferMap.end()) {
        OBJTRACK_NODE *pNode = (*itr).second;
        del_itr = itr++;
        if (pNode->parentObj == (uint64_t)(commandPool)) {  //<----------- HERE  pNode IS NULL-----<<<
            skipCall |= validate_command_buffer(device, commandPool, reinterpret_cast<VkCommandBuffer>((*del_itr).first));
            free_command_buffer(device, reinterpret_cast<VkCommandBuffer>((*del_itr).first));
        }
    }
    destroy_command_pool(device, commandPool);
    lock.unlock();
    get_dispatch_table(object_tracker_device_table_map, device)->DestroyCommandPool(device, commandPool, pAllocator);
}
```

The problem appears only when old objects are deleted during the new use of queue. In points situation looks that:
1. Create object: buffers_1, commandBuffer_1,commandPool_1, ...
2. Executing queue
3. Wait for fence
3. Create object: buffers_2, commandBuffer_2,commandPool_2, ...
4. Execute queue
5. Delete object: buffers_1, commandBuffer_1,commandPool_1, ...

When layers are off the program is working without problems. 
We get errors and crash only on some driver implementations, but after consulting with vendor it seems to be layer error.

**Comment by stroyan** [comment] 2016-07-01 14:12
That command buffer object value is not one that you would get from the unique objects layer.
You must use the unique objects layer last so the other layers are not confused by reused object ids.

**Comment by ArkadiuszSarwa** [comment] 2016-07-01 15:45
Did you mean the environment settings?
Configuration 1
> VK_INSTANCE_LAYERS=VK_INSTANCE_LAYERS=VK_LAYER_GOOGLE_threading;VK_LAYER_LUNARG_parameter_validation;VK_LAYER_LUNARG_device_limits;VK_LAYER_LUNARG_object_tracker;VK_LAYER_LUNARG_image;VK_LAYER_LUNARG_core_validation;VK_LAYER_LUNARG_swapchain;VK_LAYER_GOOGLE_unique_objects
> VK_DEVICE_LAYERS=VK_INSTANCE_LAYERS=VK_LAYER_GOOGLE_threading;VK_LAYER_LUNARG_parameter_validation;VK_LAYER_LUNARG_device_limits;VK_LAYER_LUNARG_object_tracker;VK_LAYER_LUNARG_image;VK_LAYER_LUNARG_core_validation;VK_LAYER_LUNARG_swapchain;VK_LAYER_GOOGLE_unique_objects

Configuration 2
> VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation
> VK_DEVICE_LAYERS=VK_LAYER_LUNARG_standard_validation

On the first configuration I have got only the error messages 
OBJTRACK(ERROR): object: 0x5376d70 type: 0 location: 495 msgCode: 0: Unable to remove obj 0x5376d70. Was it created? Has it already been destroyed?
OBJTRACK(ERROR): object: 0x5376d70 type: 0 location: 495 msgCode: 0: Unable to remove obj 0x5376d70. Was it created? Has it already been destroyed?

On second configuration I have got situation with crash.

**Comment by stroyan** [comment] 2016-07-01 20:02
Your first use case had a duplicate "VK_INSTANCE_LAYERS=", so it did not correctly list the threading layer.  It instead looked for a layer named "VK_INSTANCE_LAYERS=VK_LAYER_GOOGLE_threading".
A threading mistake in your calls would then leave the object tracker layer open to data corruption.

The second configuration is indeed using both the threading layer and the unique objects layer.
I was looking for a low object handle as the unique objects layer uses for non-dispatchable objects, but the VkCommandBuffer ID of 0x612e020 is actually reasonable because it is a dispatchable object that would not need to be renamed by the unique objects layer.

That message does look like a true report of a threading error.
You could check that by putting a debugger breakpoint in a DbgMessageCallback function.
The threading error callback will happen when two threads are making calls passing in the same VkCommandBuffer.  Have a look at the thread call stacks with the debugger and see what calls are being made.

**Comment by yavn** [comment] 2016-07-05 13:19
Hi, we've done a bit more debugging on this and here are some clues:

- the crash is observed in master HEAD revision (locally built binaries), on every run
- the 1.0.17.0 version built locally never crashes, but sometimes gives an error about invalid handle
- the 1.0.17.0 SDK prebuilt version never crashes nor produces any messages

It seems the driver quite often returns the same VkCommandBuffer handle, even when a new pool and a new buffer are allocated on each run. This doesn't seem a problem in its own right because once an object is freed to the pool then a new one can be allocated with the same address. I checked two driver implementations and both seem to exhibit this behavior.

The tracking layer uses dispatchable handle as a unique key into some internal structures and it seems modification of these structures is not fully protected. I've observed a situation in which driver returned the same handle which caused a problem in `alloc_command_buffer()` in `object_tracker.h`:

```
// map already has 1 entry with the same key
// the next line replaces this entry
VkCommandBufferMap[reinterpret_cast<uint64_t>(vkObj)] = pNewObjNode;
```

As a result the original entry is lost, and it isn't properly deleted in `free_command_buffer()`. I think this leads to errors later down the road.

This can be verified by setting the tracker layer to info level logging. As test progresses, more and more zombie command buffers accumulate. Note duplicate "CREATE" lines.

```
OBJTRACK(INFO): object: 0x55e0700 type: 6 location: 483 msgCode: 0: OBJ[41] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x55e0700
OBJTRACK(INFO): object: 0x55e0700 type: 6 location: 535 msgCode: 0: OBJ_STAT Destroy VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT obj 0x55e0700
    (29 total objs remain & 0 VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT objs).
OBJTRACK(INFO): object: 0x5a59de0 type: 6 location: 483 msgCode: 0: OBJ[53] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x5a59de0
OBJTRACK(INFO): object: 0x5a59de0 type: 6 location: 535 msgCode: 0: OBJ_STAT Destroy VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT obj 0x5a59de0
    (29 total objs remain & 0 VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT objs).
OBJTRACK(INFO): object: 0x5a59de0 type: 6 location: 483 msgCode: 0: OBJ[65] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x5a59de0
OBJTRACK(INFO): object: 0x5a59de0 type: 6 location: 535 msgCode: 0: OBJ_STAT Destroy VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT obj 0x5a59de0
    (29 total objs remain & 0 VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT objs).
.                          ~~~
.                           ` all good for now
.
OBJTRACK(INFO): object: 0x5a5cd40 type: 6 location: 483 msgCode: 0: OBJ[412] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x5a5cd40
OBJTRACK(INFO): object: 0x5a5cd40 type: 6 location: 483 msgCode: 0: OBJ[424] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x5a5cd40
OBJTRACK(INFO): object: 0x5a5cd40 type: 6 location: 535 msgCode: 0: OBJ_STAT Destroy VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT obj 0x5a5cd40
    (39 total objs remain & 1 VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT objs).
OBJTRACK(INFO): object: 0x5a5b590 type: 6 location: 483 msgCode: 0: OBJ[437] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x5a5b590
OBJTRACK(INFO): object: 0x5a5b590 type: 6 location: 535 msgCode: 0: OBJ_STAT Destroy VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT obj 0x5a5b590
    (30 total objs remain & 1 VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT objs).
.                          ~~~
.                           ` oops, 1 object leaked!
.
OBJTRACK(INFO): object: 0x5a5ce00 type: 6 location: 483 msgCode: 0: OBJ[1408] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x5a5ce00
OBJTRACK(INFO): object: 0x5a5ce00 type: 6 location: 483 msgCode: 0: OBJ[1420] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x5a5ce00
OBJTRACK(INFO): object: 0x5a5ce00 type: 6 location: 535 msgCode: 0: OBJ_STAT Destroy VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT obj 0x5a5ce00
    (40 total objs remain & 2 VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT objs).
.                          ~~~
.
.
OBJTRACK(INFO): object: 0x5a5ce00 type: 6 location: 483 msgCode: 0: OBJ[1504] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x5a5ce00
OBJTRACK(INFO): object: 0x5a5ce00 type: 6 location: 483 msgCode: 0: OBJ[1516] : CREATE VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT object 0x5a5ce00
OBJTRACK(INFO): object: 0x5a5ce00 type: 6 location: 535 msgCode: 0: OBJ_STAT Destroy VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT obj 0x5a5ce00
    (41 total objs remain & 3 VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT objs).
.                          ~~~
.
.
```

**Comment by mark-lunarg** [comment] 2016-07-05 14:33
The object tracker layer is being rewritten and this issue should be addressed as part of that effort.  Would you be willing to run a beta version to make sure it takes care of this issue (or to offer up a repro case for us to test against)?

**Comment by yavn** [comment] 2016-07-05 14:40
Sure, I'll be happy to help out. Other than that, I'm always using the latest build from the master branch to report errors.

**Comment by mark-lunarg** [comment] 2016-07-05 14:49
Great, I'll ping you when the PR is almost ready for prime-time.

**Comment by mark-lunarg** [comment] 2016-07-11 17:07
There's a branch on github now for PR738, can you give that a try?

**Comment by yavn** [comment] 2016-07-12 11:05
Hi, not sure if I've used the correct one, but I've merged `tobin_gh738_test` into `master` and tested with that.

So far I'm seeing the same results:
- a crash due to a null pointer in `device_data->object_map[VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT]` (`.second` is null)
- when `info` level logging is enabled, I'm seeing more and more leaked command buffers. The layer doesn't crash in this situation, but this is probably due to threads acting differently under heavy log output.

The offending test is in CTS dev branch `399-internally-synchronized-objects-tests`, the filter `dEQP-VK.synchronization.internally*`. I've observed the crash only on some hardware, but I'd rather not name and shame publicly.

**Comment by mark-lunarg** [comment] 2016-07-12 13:58
Sorry, I should have given this pointer:  #738 is the correct pull request.  The branch is mark-master-object-tracker-ungen.  In the meantime, your information on the failing test environment will be helpful and I'll run through that to see what I can find.

**Comment by mark-lunarg** [comment] 2016-07-12 15:46
Maciej, I cranked up CTS and ran these tests and haven't seen either of these issues with Master or with the new branch (though it does seem to leak fewer objects).  I am running on Nvidia Win64 -- if you're comfortable with it please mail the failing configurations to mark@lunarg.com and maybe I can tackle it that way.

**Comment by stroyan** [comment] 2016-07-12 22:45
I see what could be the cause of the "THREADING(ERROR)" complaint.
The vktSynchronizationInternallySynchronizedObjectsTests are very rapidly
destroying and creating
VkCommandPool and VkCommandBuffer objects from many threads.
While VkCommandPool objects are renamed to make them unique,
VkCommandBuffer objects are dispatchable objects which are not renamed.
A driver might reuse the handle of a recently freed VkCommandBuffer.
The threading layer may not have finished its own vkFreeCommandBuffers call
before
another thread comes along and starts to make calls with a recently
reissued handle for a new command buffer.

The object tracking layer may still have a similar problem.
Another thread could allocate and use a reused command buffer handle before
call to vkFreeCommandBuffers
finishes accounting for the first call.  It could even allocate and free a
command buffer before the previous free completes.

On Tue, Jul 12, 2016 at 9:46 AM, Mark Lobodzinski <notifications@github.com>
wrote:

> Maciej, I cranked up CTS and ran these tests and haven't seen either of
> these issues with Master or with the new branch (though it does seem to
> leak fewer objects). I am running on Nvidia Win64 -- if you're comfortable
> with it please mail the failing configurations to mark@lunarg.com and
> maybe I can tackle it that way.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/719#issuecomment-232090580>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEV7uJ6fzk81sh-f91MaTCjUyLPjIZTcks5qU7bfgaJpZM4JDEG0>
> .
>



-- 
Mike Stroyan, stroyan@google.com

**Comment by yavn** [comment] 2016-07-13 07:54
Oh right, I should've checked PRs first... I retested with the correct branch now but the results are still the same.

@stroyan, yes I think this is exactly what is happening. I observed the same in my debugging sessions.

**Comment by mark-lunarg** [comment] 2016-07-14 13:31
@yavn  -- ran updated branch yesterday (with suggested fixes from @stroyan ) on the hardware you specified on Win10 and got no OT errors.  If you get a chance please retry that updated branch again and send me any bad OT output along with the particulars and I'll keep looking into it.

**Comment by yavn** [comment] 2016-07-14 20:18
Sure, I'll retest it tomorrow once I get back in the office.

**Comment by yavn** [comment] 2016-07-15 11:44
Hey, I merged the PR branch into master as before and ran the tests a few times. This version is a bit of a mixed bag:

On the first driver (that used to work) I'm now getting these errors (but very rarely):

- DS(ERROR): object: 0x1c04 type: 19 location: 6593 msgCode: 8: Attempt to bind Pipeline 0x1c04 that doesn't exist!
- an assertion error in DestroyPipeline() (deeper in the call stack, not in layer code, so some dangling pointer dereference most likely).

The second driver (the one that was crashing) now no longer crashes, but reports the following errors (every time):

> THREADING(ERROR): object: 0x5be1450 type: 6 location: 0 msgCode: 1: THREADING ERROR : object of type VkCommandBuffer is simultaneously used in thread 4280 and thread 5756
> THREADING(ERROR): object: 0x81b0ae0 type: 6 location: 0 msgCode: 1: THREADING ERROR : object of type VkCommandBuffer is simultaneously used in thread 4280 and thread 3500
> THREADING(ERROR): object: 0x81e45e0 type: 6 location: 0 msgCode: 1: THREADING ERROR : object of type VkCommandBuffer is simultaneously used in thread 4280 and thread 5756
> THREADING(ERROR): object: 0x0 type: 25 location: 0 msgCode: 1: THREADING ERROR : object of type VkCommandPool is simultaneously used in thread 0 and thread 5756
> THREADING(ERROR): object: 0x821b6e0 type: 6 location: 0 msgCode: 1: THREADING ERROR : object of type VkCommandBuffer is simultaneously used in thread 3500 and thread 4280

Messages seem similar to those before, so I think the same issue is still present under the hood. It doesn't crash though, so that's an improvement.

**Comment by mark-lunarg** [comment] 2016-11-14 16:13
@yavn , This has been dormant for some time, have your issues been adequately addressed?  If so, please close this one.

**Comment by yavn** [comment] 2016-11-15 09:30
Hi @mark-lunarg , I can no longer observe the original abnormal behavior. Handles are now correctly reused and no objects are being leaked. I think we can close this, thank you! (I have no rights to close this directly)

**Comment by mark-lunarg** [comment] 2016-11-15 14:16
@yavn -- thanks very much for verifying the behavior!

**Closed by mark-lunarg** 2016-11-15 14:16 UTC
Labels: bug
