### ISSUE TITLE
Trying to map memory bound to image with layout different than GENERAL or PREINITIALIZED reported as an error - should be a warning.

### ISSUE THREAD

**Issue by MarcinKantochAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1466] opened 2017-02-09 10:34 UTC
Core validation reports the following error, if trying to map memory bound to image with layout different than GENERAL or PREINITIALIZED:
"ERROR: Cannot map an image with layout VK_IMAGE_LAYOUT_UNDEFINED. Only GENERAL or PREINITIALIZED are supported."

The Vulkan spec touches on the topic in several places:

Chapter 11.4

"Host access to image memory is only well-defined for images created with VK_IMAGE_TILING_LINEAR tiling and for image subresources of those images which are currently in either the VK_IMAGE_LAYOUT_PREINITIALIZED or VK_IMAGE_LAYOUT_GENERAL layout"

"VK_IMAGE_LAYOUT_UNDEFINED: Supports no device access. This layout must only be used as the initialLayout member of VkImageCreateInfo or VkAttachmentDescription, or as the oldLayout in an image transition. When transitioning out of this layout, the contents of the memory are not guaranteed to be preserved."

Chapter 11.8

"Buffers, and linear image subresources in either the VK_IMAGE_LAYOUT_PREINITIALIZED or VK_IMAGE_LAYOUT_GENERAL layouts, are host-accessible subresources. That is, the host has a well-defined addressing scheme to interpret the contents, and thus the layout of the data in memory can be consistently interpreted across aliases if each of those aliases is a host-accessible subresource."

In my opinion the spec says that mapping memory bound to an image with layout VK_IMAGE_LAYOUT_UNDEFINED or any other layout is not forbidden. The spec only says that the layout of the data in mapped memory can be predictably translated to GPU image memory layout only if the image has tiling VK_IMAGE_TILING_LINEAR and layout is GENERAL or PREINITIALIZED.

Thats why I would like to propose to change the status of the above message from ERROR to WARNING. Also a check is missing, if the image was created with VK_IMAGE_TILING_LINEAR tiling.

**Comment by lentinem** [comment] 2017-02-09 14:25
I'm not sure how you conclude that this doesn't mean using UNDEFINED in map is forbidden. It seems fairly clear that that you cannot access the memory in this state. If I recall correctly the main purpose of PREINITIALIZED is to have an initial state that can be mapped and set. Additionally, even if we assume UNDEFINED memory can be set this seems like it wouldn't be useful as transitioning from this into a useful state can result in the contents not being preserved. I'm open to hearing other opinions but at this point I'm included to say this should definitely be an error.

**Comment by mark-lunarg** [comment] 2017-02-09 15:21
@MarcinKantochAMD, do you have in mind some practical use case for mapping memory in the IMAGE_LAYOUT_UNDEFINED state?

**Comment by MarcinKantochAMD** [comment] 2017-02-09 15:31
I can't find any. On the other hand drivers do allow to map such memory and perform operations on it, no error is caused by such behavior.

**Comment by phaulos** [comment] 2017-02-09 15:54
This came up in tests and in them we want to test *everything* that is valid and within spec, regardless of whether it makes apparent sense or not.

Even if you can't use values written by CPU as an image afterwards, it is perfectly legal for the CPU to use the memory for other purposes. Thus validation must not generate an error here.

**Comment by jeremy-lunarg** [comment] 2017-02-09 15:59
I agree with @lentinem, but I also think the spec could be improved. In one sentence it takes a firm stance: "This layout must only be used as the
initialLayout member of VkImageCreateInfo or VkAttachmentDescription, or as the oldLayout in
an image transition." But in the very next sentence: "When transitioning out of this layout, the contents of the memory are not guaranteed to be
preserved."; it leaves the door open for a more liberal interpretation.

**Comment by jeremy-lunarg** [comment] 2017-02-09 15:59
Sorry, I did not mean to close the issue. ;)

**Comment by mark-lunarg** [comment] 2017-02-09 16:11
In internal discussions we can see solid cases for each interpretation.  However, at least at this time, the evidence doesn't seem overwhelming enough to make the error->warning changes without some feedback from the working group as to their intent. @MarcinKantochAMD, can you raise this issue with the WG in Vulkan-Docs and link to it here?

**Comment by lentinem** [comment] 2017-02-09 16:14
After many readings, I agree with Mark that it is not entirely clear if this is allowed from the current wording as I can see it both ways. However, I think the potentially bigger issue is if there is no valid use case and doing this can only hurt users why would we allow this in the spec? If we assume for the moment that this is allowed currently I would still advocate disallowing it going forward and changing the spec.

**Comment by phaulos** [comment] 2017-02-09 21:19
On the spec that @jeremy-lunarg quoted: "When transitioning out of this layout, the contents of the memory are not guaranteed to be preserved."

The tests do not expect the memory contents to be preserved after a layout transition. But that doesn't mean mapping and writing to (and reading from) the memory on CPU would be disallowed. You can use the memory for some other completely unrelated purpose (store a string that you printf() out for example) and only later decide to actually use the image for something. As long as you are not assuming that whatever you wrote to the memory would be preserved spec is not violated at all.

If VkDeviceMemory is host-visible, you can map it at any point, and do whatever you want with it at any time (as you would do with malloc()'d memory). Various Vulkan commands, when executed, will cause the contents (or state of caches) to become undefined of course. As long as you take that into account your application will work correctly and stay fully within spec.

**Comment by karl-lunarg** [comment] 2017-02-10 00:51
I think that the problem is with the wording:

> Host access to image memory is only well-defined for images created with​...

​not "well-defined" for ​LAYOUT_UNDEFINED means all bets are off and anything can happen.  "well-defined" is probably not a great term to use in a spec.

The spec's Glossary also says:

> Host-Accessible Subresource
> A buffer, or a linear image subresource in either the VK_IMAGE_LAYOUT_PREINITIALIZED or VK_IMAGE_LAYOUT_GENERAL layout. Host-accessible subresources have a well-defined addressing scheme which can be used by the host.

This suggests that that in order for a subresource to be host-accessible, it needs to be LAYOUT_PREINITIALIZED or LAYOUT_GENERAL.  Since mapping is required for the host to access the memory, then it now seems reasonable to report a validation error if trying to map memory with LAYOUT_UNDEFINED.

And since this is a Glossary item, this definition suggests that the overall across-the-spec **intent** is to allow mapping for only the listed layouts.

Maybe the CTS shouldn't even be doing write/read tests on mapped memory with an undefined layout.  "not well-defined" can be anything, including making even the simplest write-reads not work.

Yes, we know that most drivers/hardware work as expected when mapped with undefined layout. 
But I could build a device that has a pixel-shifter-swizzler on the channel between the host bus and the local discrete device memory.  This p-s-s has the capability to swap color channels or maybe even convert to OPTIMAL layout on the fly (thus allowing host access in OPTIMAL layout).  But the point is that this p-s-s is programmable and if the image is left in undefined layout, the driver may not bother to program the p-s-s and leave it in a state where the host won't be reading back what it read.  And that would fail a CTS test.

**Comment by phaulos** [comment] 2017-02-10 01:24
So, you are arguing that once VkDeviceMemory gets associated with an image, doing CPU writes/reads suddenly cease to work once you bind it to VkImage that is not in GENERAL or PREINITIALIZED layout?

It is perfectly legal for host to create VkDeviceMemory and map it without binding it to any Vulkan resource. That mapped memory must work like any other piece of malloc()'d memory. It would be really surprising if merely binding it to VkImage somehow affected host's ability to access the memory area.

**Comment by MarcinKantochAMD** [comment] 2017-02-10 13:33
Asked the question in Vulkan WG. Link to the issue: https://gitlab.khronos.org/vulkan/vulkan/issues/678

**Comment by karl-lunarg** [comment] 2017-02-10 13:51
@MarcinKantochAMD Thanks!  I think this does need spec clarification to resolve.

@phaulos Yes, I could conjure up a machine that behaves that way - a bind of memory to an image would move the memory into an image-only pool that can't be accessed from the host until a layout transition to one of the host-accessible layouts is performed.

Personally, I agree that the host should have access to the memory even when bound to an image with undefined layout.  But objectively, the spec says (pretty clearly) that this host access is not well-defined.

**Comment by phaulos** [comment] 2017-02-10 16:54
If having memory bound to VkImage (not in GENERAL | PREINITIALIZED layout) makes CPU reads/writes undefined behavior (and illegal) then that would severely limit resource aliasing.

In section 11.8. Memory Aliasing spec does say that it is legal to bind same memory to a VkImage and VkBuffer for instance. So even if memory is already bound to LAYOUT_UNDEFINED VkImage, it can be bound to VkBuffer as well, making access scheme (as far buffer is concerned) from host well-defined again, as long as the use of the different aliases are separated by "separated by a memory dependency using the appropriate access types".

There's nothing saying that accessing contents of mapped VkBuffer from host is invalid if the memory is also bound to VkImage that is not in appropriate layout.

**Comment by karl-lunarg** [comment] 2017-02-10 18:23
True, and good point.  

The discussion over in gitlab is saying that the intent behind "not well-defined" is that you should be allowed to map (and read/write, I suppose) but the behavior of the read/writes, except perhaps reading back memory after a write,  is somewhat unpredictable.

There's also some agreement that the spec wording could be better here.  And we shouldn't have to loop through the aliasing section in order to discover something that clarifies what is allowed here.

We'll probably propose a spec clarification.

Otherwise, @lentinem , do you want to move these checks to a warning severity or assign this to someone?

**Comment by MarcinKantochAMD** [comment] 2017-02-16 12:41
@lentinem Just wanted to ask if the fix is being prepared?

**Comment by lentinem** [comment] 2017-02-16 14:16
A fix has been checked in but I wanted to investigate more to see if there is a reasonable use case for this functionality before closing the bug. If there isn't, we would want to change it back to an error (note that validation errors can technically be valid according to the spec if there is no reasonable use case for an application as our primary goal is to protect applications).

However, I believe I'm fairly convinced at this point that there are potentially reasonable use cases in which an app would map undefined memory so I'm going to leave this as a warning and close the issue.

**Closed by lentinem** 2017-02-16 14:16 UTC
Labels: question
