### ISSUE TITLE
Linux build failure due to outdated broken glslang revision dependency.

### ISSUE THREAD

**Issue by HypnoGenX** [KhronosGroup/Vulkan-LoaderAndValidationLayers#681] opened 2016-06-23 12:17 UTC
As first reported here; https://github.com/KhronosGroup/glslang/issues/344

The specific glslang revision pulled in by https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/glslang_revision (4678ca9dacfec7a084dbc69bbe568bdad6889f1b at time of writing) fails to build on Linux. The issue is fixed in the current https://github.com/KhronosGroup/glslang HEAD, and probably earlier.

https://github.com/LunarG/VulkanSamples has the exact same issue, so I'm duplicating this bug report there.

**Comment by karl-lunarg** [comment] 2016-06-23 14:24
This revision of glslang builds fine on Ubuntu systems (14.04 LTS and 16.04 LTS).  It seems that the failing builds are on Arch Linux g++ 5.3 (https://github.com/KhronosGroup/glslang/issues/171).

We update the glslang revision that LoaderAndValidationLayers, VulkanTools, and VulkanSamples use at about the same frequency that LunarG releases SDKs.   We were unable to bump it for a pending SDK release due to a failure in one of our tests, introduced by a change in glslang.  Since we had not completed problem determination to the point of understanding the root cause, we opted to stay at this revision.  The investigation result was that one IHV driver couldn't deal with a corrective fix applied to glslang.

Since we have recently determined that the problem isn't due to glslang itself, we'll soon be bumping the revision, which should address the Arch Linux g++ 5.3 problem.

**Comment by karl-lunarg** [comment] 2016-06-23 15:29
Also:  This [fix](https://github.com/KhronosGroup/glslang/commit/880bf36cacee1cfce7d5d94991eb18c9e2d59d39) apparently is also needed for Ubuntu 16.10 as well as Arch Linux, the common item being the g++ version.

**Comment by karl-lunarg** [comment] 2016-07-01 14:18
The glslang commit involved here is https://github.com/KhronosGroup/glslang/commit/a5c33d6ffb34ccede5b233bc724c907166b6e479 (SPV: Fix issue #320: Fetch needs to extract the image  https://github.com/KhronosGroup/glslang/issues/320).

The problem is that this fix causes problems with at least 2 IHV drivers.  The problem shows up in a LunarG sample involving texel fetch.

We'd like to delay updating the glslang revision until the IHVs have driver fixes.  These driver fixes are in progress.

A reasonable workaround in the meantime for the compilation failure is to cherry-pick https://github.com/KhronosGroup/glslang/commit/880bf36cacee1cfce7d5d94991eb18c9e2d59d39.

**Comment by karl-lunarg** [comment] 2016-07-07 16:48
It looks like the IHV drivers won't be fixed until July 18 at the earliest, so I've added code to the update_external_sources scripts to patch glslang with the above-mentioned commit (https://github.com/KhronosGroup/glslang/commit/880bf36cacee1cfce7d5d94991eb18c9e2d59d39).

This should provide relief for those using the g++ 5.3 toolchain.

**Closed by karl-lunarg** 2016-07-07 16:48 UTC
Labels: bug
