### ISSUE TITLE
Compile time error: expected ‘)’ before ‘PRIx64’

### ISSUE THREAD

**Issue by PabloBrubeck** [KhronosGroup/Vulkan-LoaderAndValidationLayers#316] opened 2016-04-13 01:23 UTC
Error when running dbuild/make

```
Building CXX object layers/CMakeFiles/VkLayer_utils.dir/vk_layer_utils.cpp.o
In file included from /home/pbrubeck/Vulkan-LoaderAndValidationLayers/layers/vk_layer_utils.h:31:0,
                 from /home/pbrubeck/Vulkan-LoaderAndValidationLayers/layers/vk_layer_utils.cpp:33:
/home/pbrubeck/Vulkan-LoaderAndValidationLayers/layers/vk_layer_logging.h: In function ‘VkBool32 log_callback(VkFlags, VkDebugReportObjectTypeEXT, uint64_t, size_t, int32_t, const char*, const char*, void*)’:
/home/pbrubeck/Vulkan-LoaderAndValidationLayers/layers/vk_layer_logging.h:265:53: error: expected ‘)’ before ‘PRIx64’
     fprintf((FILE *)pUserData, "%s(%s): object: %#" PRIx64 " type: %d location: %lu msgCode: %d: %s\n", pLayerPrefix, msg_flags,
                                                     ^
make[2]: *** [layers/CMakeFiles/VkLayer_utils.dir/vk_layer_utils.cpp.o] Error 1
make[1]: *** [layers/CMakeFiles/VkLayer_utils.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by PabloBrubeck** [comment] 2016-04-13 01:29
My specs
Centos 7.2
Kernel 3.10.0-327.13.1.el7.x86_64
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
Cmake version 2.8.12

**Comment by karl-lunarg** [comment] 2016-04-13 14:21
This code builds fine with all the tool chains we are using.  If you remove the "#", does the problem go away for you?

**Comment by karl-lunarg** [comment] 2016-05-04 22:15
This is a C99 feature and it seems possible that -std=c99 needs to be specified as a compiler option for the version of gcc used here.

Closing based on age, lack of follow-up, and the likelihood that the above explanation will help.

**Comment by Delwin9999** [comment] 2016-05-06 13:22
I get this as well under the current master.

gcc 4.9.2
CentOS 6.8
cmake version 2.8.12.2
kernel 2.6.32-573.26.1.el6.x86_64

The problem is that the header vk_layer_logging.h is being included from c++ files.   vk_layer_logging.h uses the c99 header include inttypes.h rather than the C++ version cinttypes.  Given that vk_layer_logging.h is in C++ not C I believe that the proper fix would be to switch to C++ headers.

**Comment by karl-lunarg** [comment] 2016-05-06 15:56
Thanks, I saw that cinttypes might be a possible solution, but couldn't reconcile it working with other compilers.  I'll reopen and look at this again.

**Comment by karl-lunarg** [comment] 2016-05-10 17:48
Fixes pushed to master in https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/37fb5d229d5163e1c1f817810dafd5e3e4c33a1d.

This repo builds now on CentOS 7 with gcc 4.8.5 and cmake 2.8.12.

**Closed by karl-lunarg** 2016-05-10 17:48 UTC
Labels: question

**Comment by Delwin9999** [comment] 2017-01-31 18:27
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/414e9a4117b500eac650d8b8f01a6e1b22d05aae#diff-81e715a0f07036945919bca76416f7df

This commit broke this again by removing the # sign at the end of the first string before the PRIx64.
