### ISSUE TITLE
Null pointer access in PreCallValidateBindBufferMemory

### ISSUE THREAD

**Issue by asuonpaa** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2241] opened 2017-11-30 12:23 UTC
I'm seeing a null pointer access in core_validation.cpp line 3758 function PreCallValidateBindBufferMemory. There mem_info is being used without checking if it's null:
```
// Validate memory requirements size
        if (buffer_state->requirements.size > (mem_info->alloc_info.allocationSize - memoryOffset)) {
```

Earlier in the same function it is checked:
```
// Validate bound memory range information
        auto mem_info = GetMemObjInfo(dev_data, mem);
        if (mem_info) {
```

**Comment by mark-lunarg** [comment] 2017-11-30 14:34
@asuonpaa, were there any validation errors prior to reaching this point?  The Core Validation layer (to a large but not complete extent) relies on other layers to do these types of checks, and as you have noticed does not perform them pervasively.  If an invalid access was encountered with no other validation errors then we **would** need to make a change here -- let us know!

**Comment by asuonpaa** [comment] 2017-12-01 06:58
@mark-lunarg : Thanks for your help. I'm not seeing errors before this. Also if that object would be guaranteed to not be null by some other layer, then the existing checks of mem_info would be unnecessary. So IMO a consistent solution is to check the pointer at each location it's being used in that function.

**Comment by mark-lunarg** [comment] 2017-12-01 15:59
@asuonpaa, I see.  Is there any way you can get us a straightforward repro case, or some instructions on how to reproduce this issue -- this does sound like a layer bug, one way or the other.  As for the Null checks, for the most part they should be unnecessar, and the time it would take to scrub the layers of unnecessary checks is not near the top of the priority list.

**Comment by mark-lunarg** [comment] 2017-12-06 15:58
@asuonpaa, is there any way you can share a test case?

**Comment by tobine** [comment] 2017-12-06 20:56
Note that having a valid VkDeviceMemory param in vkBindBufferMemory() is VALIDATION_ERROR_1700c601 which is checked in object_tracker.

**Comment by asuonpaa** [comment] 2017-12-13 11:36
The root cause seems to be the fact I'm using multiple device and allocator objects. Most likely those are confusing the validator. I'm going to roll back to using only a single device object so the original validator issue is no longer bothering me.

**Comment by jzulauf-lunarg** [comment] 2018-01-12 15:27
There is a sparse memory CTS with the same issue... I have a fix pending in https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2336 if you'd like to review/comment/try.

**Comment by jzulauf-lunarg** [comment] 2018-01-12 15:57
Regarding: 
"The root cause seems to be the fact I'm using multiple device and allocator objects. Most likely those are confusing the validator."

AFAICT the memory and buffer must be associated with the device to be valid. From the Valid Usage (Implicit) for vkBindBufferMemory.  

- buffer must have been created, allocated, or retrieved from device (VUID-vkBindBufferMemory-buffer-parent)
- memory must have been created, allocated, or retrieved from device (VUID-vkBindBufferMemory-memory-parent)

So, if you try to bind memory from one device using a different VkDevice, the validator will look at the VkMemory for the passed VkDevice, and (IIAC) correctly not find it associated with the VkDevice.

**Comment by jzulauf-lunarg** [comment] 2018-01-12 18:33
Fix merged addressing the exact line referenced.

**Closed by jzulauf-lunarg** 2018-01-12 18:33 UTC
Labels: help wanted
