### ISSUE TITLE
Redundant error messages when calling vkQueueSubmit on a destroyed buffer.

### ISSUE THREAD

**Issue by renelindsay** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1292] opened 2016-12-20 21:39 UTC
Redundant, unexpected error message in file: tests/layers/layer_validation_tests.cpp, 
test: vkLayerTest.InvalidCmdBufferBufferDestroyed.

When vkQueueSubmit is called on a destroyed buffer, it produces the following 2 error messages:

  Unexpected: Cannot submit cmd buffer using deleted buffer 0x2.
  Unexpected: You are submitting command buffer 0x2b97920 that is invalid because bound buffer 0x2 was destroyed.

The second error is expected by the test, but the first  is not.
This is a problem in the validation layers, not the test.
Is one of these error messages redundant?

**Comment by mark-lunarg** [comment] 2016-12-20 22:14
Duplicate of issue #945.

**Comment by jeremy-lunarg** [comment] 2016-12-20 22:57
I was under the impression that #945 is generating the erroneous "Attempt to free command buffer which is in use" message. i.e. I think don't believe this is a duplicate issue.

**Comment by renelindsay** [comment] 2016-12-20 23:36
Yes, it doesn't sound like a duplicate to me either.

**Comment by mark-lunarg** [comment] 2016-12-21 15:44
Looked into it this morning, this is a duplicate of #945.  That issue does not call out a specific error, but a class of errors stemming from the fact that state updates and validation are intertwined for command buffer state updates.  The queuesubmit/resource tracking stuff needs to be separated (as @chrisforbes suggests) which should take care of scads of errors in this class.

**Closed by mark-lunarg** 2016-12-21 15:44 UTC
