### ISSUE TITLE
[CTS] Access violation in unique_objects

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#439] opened 2016-04-27 19:00 UTC
Running dEQP-VK.api.object_management.max_concurrent.instance followed by dEQP-VK.api.object_management.max_concurrent.device I intermittently see an access violation in unique_objects explicit_DestroyDevice in get_dispatch_key.  The message says the access violation occurs when reading the address that corresponds to the object pointer.  This is a multithreaded test and the failure is difficult to reproduce - it happens around once in every 25 times the pair of tests are run.

**Comment by karl-lunarg** [comment] 2016-04-29 16:00
I got this to happen easily by using this list of tests:

```
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_1d
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_2d
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_3d
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_view_1d
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_view_1d_arr
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_view_2d
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_view_2d_arr
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_view_cube
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_view_cube_arr
dEQP-VK.api.object_management.multithreaded_per_thread_resources.image_view_3d

```

The standard validation layer is used.
Stack trace:
```
0	??			0x7ffff4e61c6b	
1	??			0x7ffff4e62069	
2	vkDestroyImageView	unique_objects.cpp	836	0x7ffff36d95ef	
3	vkDestroyImageView	core_validation.cpp	5771	0x7ffff2e58b5c	
4	vkDestroyImageView	object_tracker.cpp	5325	0x7ffff26a3705	
5	vkDestroyImageView	parameter_validation.cpp	2423	0x7ffff21e2211	
6	vkDestroyImageView	thread_check.h	857	0x7ffff1efcd14	
7	vk::DeviceDriver::destroyImageView	vkDeviceDriverImpl.inl	217	0x11faeaa	
8	vk::refdetails::Deleter<vk::Handle<(vk::HandleType)13>>::operator()	vkRefUtilImpl.inl	58	0x11f29a6	
9	vk::refdetails::RefBase<vk::Handle<(vk::HandleType)13>>::reset	vkRef.hpp	251	0xb2fc75	
10	vk::refdetails::RefBase<vk::Handle<(vk::HandleType)13>>::~RefBase	vkRef.hpp	244	0xb2c966	
11	vk::refdetails::Unique<vk::Handle<(vk::HandleType)13>>::~Unique	vkRef.hpp	324	0xb2b676	
12	vkt::api::(anonymous namespace)::CreateThread<vkt::api::(anonymous namespace)::ImageView>::runThread	vktApiObjectManagementTests.cpp	1995	0xc0381e	
13	vkt::api::(anonymous namespace)::ThreadGroupThread::run	vktApiObjectManagementTests.cpp	193	0xb9f65f	
14	de::threadFunc	deThread.cpp	72	0x1414a8b	
15	startThread	deThreadUnix.c	65	0x141e842	
16	start_thread	/usr/lib/debug/lib/x86_64-linux-gnu/libpthread-2.21.so	333	0x7ffff747c6aa	
17	clone	/usr/lib/debug/lib/x86_64-linux-gnu/libc-2.21.so	109	0x7ffff66f6e9d	

```

**Comment by dustin-lunarg** [comment] 2016-04-29 18:13
I came across an access violation in DestroyDevice when using Application Verifier to debug a different issue.  I created a PR #456 to address the issue.  It may address the same problem that Tony is reporting here.

**Comment by tobine** [comment] 2016-04-29 18:21
Just pushed #456 to master. I ran Karl's list of 10 tests and don't see a failure. Tony can you check and close if fixed?

**Comment by karl-lunarg** [comment] 2016-04-29 20:05
The problem is still occurring.   

When it fails at the call to the downstream DestroyImage, local_image is a value that exists in the unique_id_mapping, and it maps to a valid looking handle.  But the value of image is 0, meaning that a 0 is passed downstream.

```
VK_LAYER_EXPORT VKAPI_ATTR void VKAPI_CALL vkDestroyImage(VkDevice device, VkImage image, const VkAllocationCallbacks* pAllocator)
{
// CODEGEN : file /home/karl/src/Vulkan-LoaderAndValidationLayers/vk-layer-generate.py line #1560
    layer_data *my_map_data = get_my_data_ptr(get_dispatch_key(device), layer_data_map);
// STRUCT USES:['image']
    uint64_t local_image = reinterpret_cast<uint64_t &>(image);
    image = (VkImage)my_map_data->unique_id_mapping[local_image];
// CODEGEN : file /home/karl/src/Vulkan-LoaderAndValidationLayers/vk-layer-generate.py line #1665
    get_dispatch_table(unique_objects_device_table_map, device)->DestroyImage(device, image, pAllocator);
// CODEGEN : file /home/karl/src/Vulkan-LoaderAndValidationLayers/vk-layer-generate.py line #1653
    std::lock_guard<std::mutex> lock(global_lock);
    my_map_data->unique_id_mapping.erase(local_image);
}

```

I hacked the (generated) code to move the lock to above the 

`image = (VkImage)my_map_data->unique_id_mapping[local_image];`

and that seems to help.  So it may well be a locking issue.   I'm trying to figure out how to change codegen to make this change.

Tobin, does this seem reasonable?

I note that the lock is requested before inserting a mapping, in functions like vkCreateShaderModule.

**Comment by tobine** [comment] 2016-04-29 20:42
Good work, Karl. Yeah, missing the lock for the pre_call portion of destroy functions. We need to insert a lock and then unlock into "pre_call_txt" around [this](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/vk-layer-generate.py#L1586) for loop section of code in vk-layer-generate.py. The "pre_call_txt" is what appears before the call down the chain, so we need to unlock before calling down the chain.

Give that code a shot and assign to me if you have issues.

**Comment by karl-lunarg** [comment] 2016-04-29 23:26
OK, I came up with a fix that I like.  I ran the 120 multithreaded tests in CTS and they all pass, so I pushed the fix to master.  My test server will run the entire suite tonight.

**Closed by karl-lunarg** 2016-04-29 23:26 UTC
Labels: bug
