### ISSUE TITLE
ShaderValidation: may has incorrect check for read only buffers

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2546] opened 2018-04-04 07:10 UTC
Hi,

we are getting this error:  

> Error: (objectType=0, object=0x0, location=0, errorCode=15) Validation: Object: VK_NULL_HANDLE (Type = 0) | Shader requires VkPhysicalDeviceFeatures::vertexPipelineStoresAndAtomics but is not enabled on the device

Our baseline is DX11 HLSL 5 - it has only support for UAV resources in pixel and compute shaders. We translate the HLSL into GLSL and let glslang do the transformation to Spir-V. We validated the GLSL and it only correctly emits storage objects as readonly for vertex shaders.
So we where surprised to see this error.

Here is an example:
[spir-v dissaembly](https://drive.google.com/file/d/1TzTzDJ6dtBGaU8fMACO_3OJct1MBhKUk/view?usp=sharing)
[source glsl](https://drive.google.com/file/d/1rgaZJTNwBLtiLOTi-2xYOac4Kjx3qTM-/view?usp=sharing)

The resource binding slots/sets are different as they are rearranged in the glslang ioremap phase to compact the descriptor sets.

**Comment by mark-lunarg** [comment] 2018-04-04 15:15
@chrisforbes, would you be willing/able to triage this one?

**Comment by chrisforbes** [comment] 2018-04-06 22:15
Closing as duplicate of #2526.

**Closed by chrisforbes** 2018-04-06 22:15 UTC

**Comment by chrisforbes** [comment] 2018-04-10 16:51
@mark-lunarg I've got a plan for fixing this now, but have my hands full with another project. How urgent is fixing this?
