### ISSUE TITLE
windowsRuntimeInstaller fails on Windows in Safe Mode

### ISSUE THREAD

**Issue by scyganINTEL** [KhronosGroup/Vulkan-LoaderAndValidationLayers#746] opened 2016-07-12 15:32 UTC
VulkanRTInstaller.exe fails to install the loader, if Windows is booted into `Safe Mode`. 

This is an important use case, especially considering the case VulkanRTInstaller.exe is integrated into driver, that system may automatically revert to using Safe Mode recovery.

Failure, signalized by message box with errorcode:65,  happens around line 449  of InstallerRT.nsi, so ConfigLayersAndVulkanDLL.ps1 script is propably to blame.

**Comment by davidlunarg** [comment] 2016-07-12 15:43
What version of the RT installer are you using?

**Comment by scyganINTEL** [comment] 2016-07-12 15:48
13, should I expect different behavior on more recent version?

**Comment by davidlunarg** [comment] 2016-07-12 16:04
The way the powershell script is invoked was changed in 1.0.17.0, so it might be worth trying that version. We'll try both 1.0.13.1 and 1.0.17.0 in Safe Mode.

**Comment by lenny-lunarg** [comment] 2016-07-12 16:22
I just tried running both the 1.0.13.0 and the 1.0.17.0 runtime installers in safe mode, and both of them ran just fine. I was using Windows 10, 64 bit. What version of windows were you running? Also, are you running general safe mode or are any other options enabled?

**Comment by lenny-lunarg** [comment] 2016-09-15 16:57
I haven't been able to reproduce this issue. Furthurmore, we replaced the ConfigLayersAndVulkanDLL.ps1 script with an executable a few weeks back, so I'm closing this issue. If we have further issues, we can reopen or just create a new issue (since the issue would probably completely different internally).

**Closed by lenny-lunarg** 2016-09-15 16:57 UTC
Labels: bug
