### ISSUE TITLE
Vulkan Validation Errors should show Handles when possible.

### ISSUE THREAD

**Issue by jcoder58** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1435] opened 2017-02-01 18:25 UTC
I received this validation error from layer DS (which layer?):

     Vulkan: [Error] Error: ObjectType: Device | object: 170673199952 | location: 11734 | messageCode: 92 | message: vkCreateSwapchainKHR(): surface has an existing swapchain other than oldSwapchain | layerPrefix: DS
     Vulkan: [Error] Error: ObjectType: SwapchainKhr | object: 170739873064 | location: 3 | messageCode: 0 | message: vkCreateSwapchainKHR: internal drawable creation failed | layerPrefix: Driver

It would help if the first message showed both the swapchain handle attached to the surface, as well as the one I passed in the oldSwapchain field.  The handle is shown earlier when I create the swapchain so it make it easier to track down this bug if I could see it here..

**Comment by mark-lunarg** [comment] 2017-03-13 18:14
This is a duplicate of issue #1406.

**Closed by mark-lunarg** 2017-03-13 18:14 UTC
Labels: enhancement
