### ISSUE TITLE
Tracked memory of resolve attachments are not updated

### ISSUE THREAD

**Issue by FslNopper** [KhronosGroup/Vulkan-LoaderAndValidationLayers#356] opened 2016-04-15 12:50 UTC
As soon as vkCmdNextSubpass or vkCmdEndRenderPass is called, the memory of the resolve attachments bound to the current sub pass should be set as "written".

**Comment by McNopper** [comment] 2016-04-20 15:25
Actually, the problem does occur as soon as MSAA is used.

**Comment by lentinem** [comment] 2016-04-29 22:01
I'm a bit confused by this. This should be happening. Resolve attachments aren't really any different from any other attachment and get set when stored. If you aren't seeing that can you provide more info as to how to repro this?

**Comment by McNopper** [comment] 2016-04-30 06:03
You can reproduce it with my Vulkan example 9: https://github.com/McNopper/Vulkan/tree/master/VKTS_Example09
I will revisit my code, as the latest SDK is out but I am still sure the behaviour in the validation is sitll not correct.

**Comment by McNopper** [comment] 2016-05-05 20:54
"vkQueuePresentKHR(): Cannot read invalid swapchain image x, please fill the memory before using."

The problem is, that the swap chain images are filled by the driver by resolving MSAA. Currently, vkCmdNextSubpass or vkCmdEndRenderPass do not check the resolve attachments and mark the target images as filled/valid.

**Comment by lentinem** [comment] 2016-05-13 21:08
So the issue here is on line 1194 in Example.cpp for Example09 you are telling the driver to not store the image. If you change that line from VK_ATTACHMENT_STORE_OP_DONT_CARE to VK_ATTACHMENT_STORE_OP_STORE it works.

**Comment by McNopper** [comment] 2016-05-14 06:35
You are right, it is not there.
Hmm, I have the entry in my other examples.

**Closed** 2016-05-15 22:52 UTC
Labels: help wanted
