### ISSUE TITLE
loader: Bad free() when running Hologram -v

### ISSUE THREAD

**Issue by jon-lunarg** [KhronosGroup/Vulkan-LoaderAndValidationLayers#31] opened 2016-02-24 18:00 UTC
In testing the fix for standard_validation, I reliably got an assert error when calling DestroySurfaceKHR->loader_heap_free->free(pMemory). The call works fine if I don't specify "-v" to Hologram to turn on validation. This is on Windows 7, Nvidia. Note that to enable validation properly in Hologram, you need to add a line to the Shell::Shell() constructor:

instance_layers_.push_back("VK_LAYER_LUNARG_standard_validation");

**Comment by karl-lunarg** [comment] 2016-02-29 18:12
I could not reproduce this on Friday (using latest code on Win 10 / nvidia).  Tony says he saw it once early last week but has not seen it lately.  Tony just tried it again today and could not reproduce.  It is possible that some other fix fixed this issue.  Closing.

**Closed by karl-lunarg** 2016-02-29 18:12 UTC
