### ISSUE TITLE
Improve validation of non-sparse resource bindings before usage

### ISSUE THREAD

**Issue by kspagnoli** [KhronosGroup/Vulkan-LoaderAndValidationLayers#721] opened 2016-07-02 03:28 UTC
Section of 11.6 (Resource Memory Association) of the Vulkan specification defines a number of device memory binding rules that are currently unchecked by the validation layer:

> Non-sparse resources must be bound completely and contiguously to a single VkDeviceMemory object before the resource is passed as a parameter to any of the following operations:
> 
> - creating image or buffer views
> - updating descriptor sets
> - recording commands in a command buffer
> 
> Once bound, the memory binding is immutable for the lifetime of the resource.

These rules are are easy to overlook and potentially catastrophic if violated. Ideally, the validation layer would ensure memory binding before usage in these scenarios.

**Comment by tobine** [comment] 2016-08-09 14:44
Dupe of #663 
Most of these are now handled and I'm assigned to finish up some remaining cases related to resources bound to descriptor sets that are bound to cmd buffers

**Closed by tobine** 2016-08-09 14:44 UTC
Labels: enhancement
