### ISSUE TITLE
VK_ERROR_INITIALIZATION_FAILED with 280x

### ISSUE THREAD

**Issue by CrisBRM** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2152] opened 2017-10-21 15:15 UTC
No version has ever worked for me. Compiled git master and it still failed.
Kernel was built with CONFIG_DRM_AMDGPU_SI=y and the driver is Mesa (17.2.3, though I have also tried git master, to no avail).
Build flags: ```cmake -H. -Bdbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr```

[run_all_tests.log](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/1404242/run_all_tests.log)
[vulkaninfo.log](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/1404220/vulkaninfo.log)
[glxinfo.log](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/1404221/glxinfo.log)

```
λ space dbuild → λ git master → ./demos/cube 
cube: /home/desktop/git-projects/Vulkan-LoaderAndValidationLayers/demos/cube.c:3312: demo_init_vk: Assertion `!err && gpu_count > 0' failed.
[1]    12130 abort (core dumped)  ./demos/cube
```

```
λ space dbuild → λ git master → ./demos/smoketest 
terminate called after throwing an instance of 'std::runtime_error'
  what():  VkResult -3 returned
[1]    12141 abort (core dumped)  ./demos/smoketest
```

```
λ space dbuild → λ git master → ./demos/cubepp 
cubepp: /home/desktop/git-projects/Vulkan-LoaderAndValidationLayers/demos/cube.cpp:1212: void Demo::init_vk(): Assertion `result == vk::Result::eSuccess' failed.
[1]    12150 abort (core dumped)  ./demos/cubepp
```

**Comment by lenny-lunarg** [comment] 2017-10-23 15:40
Do you know where Mesa is putting its json manifest files for Vulkan to locate? I ask this because your vulkaninfo log looks to me like it's not finding a driver. The vulkan loader searches certain paths ([listed here](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/blob/master/loader/LoaderAndLayerInterface.md#icd-discovery-on-linux)) to find the available drivers. When you run vulkaninfo, you normally see a message for each of these files that is found. For example, I see the message:

```
INFO: [loader] Code 0 : Found ICD manifest file /etc/vulkan/icd.d/amd_icd64.json, version "1.0.0"
```

This message normally occurs between printing the Vulkan version and listing the instance extensions, so it should happen before the crash that you're seeing. You shouldn't see an identical message to mine, since you're using Mesa and I'm using amdgpu-pro, but you should be seeing something similar.

**Comment by CrisBRM** [comment] 2017-10-23 15:46
Yes, they're in /usr/share/vulkan/icd.d. radeon_icd.x86_64.json is there. Furthermore, I ran 

```
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
export VK_LAYER_PATH=/home/desktop/git-projects/Vulkan-LoaderAndValidationLayers/dbuild/layers
export LD_LIBRARY_PATH=/home/desktop/git-projects/Vulkan-LoaderAndValidationLayers/dbuild/loader
```
before running the tests, just in case.

Contents of radeon_icd.x86_64.json are:

```
{
    "file_format_version": "1.0.0",
    "ICD": {
        "library_path": "/usr/lib64/libvulkan_radeon.so",
        "api_version": "1.0.3"
    }
}
```

**Comment by lenny-lunarg** [comment] 2017-10-23 15:58
Well that all looks exactly like it should. Could I get you to set one more environment variable before you run:

```
export VK_LOADER_DEBUG=all
```

This will get the loader to print out every debug message it has available. Then if you could run vulkaninfo with that and post the output here, that'll (hopefully) give me a bunch more info.

**Comment by CrisBRM** [comment] 2017-10-23 16:02
[vulkaninfo.log](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/1407854/vulkaninfo.log)
There you go.

**Comment by lenny-lunarg** [comment] 2017-10-23 17:02
Thanks for the log. I still haven't been able to reproduce this on a Mesa system so it's hard for me to be completely certain, but it appears that what's happening is that the loader is finding and loading the driver just fine. The error doesn't occur until until the application calls `vkEnumeratePhysicalDevices`. At that point, the driver is returning the `VK_ERROR_INITIALIZATION_FAILED` error. It appears that the first call into the driver is actually working just fine, but the loader calls `vkEnumeratePhysicalDevices` twice (once to get the count and once to get the content) and only the second call fails. The loader just passes this error up to the user.

Unfortunately, I can't provide any insight into what's going on inside the driver, since we don't work on that. Since I'm pretty sure that this is a driver or configuration issue, I'm going to close this issue. My advice would be to re-file the issue with Mesa. If you do find more evidence to indicate that there is a loader bug I can reopen the issue, but the error is definitely originating in the driver.

**Closed by lenny-lunarg** 2017-10-23 17:02 UTC

**Comment by CrisBRM** [comment] 2017-10-23 18:05
Thanks for the quick response. I will refile it with mesa and see what happens.

**Comment by eloj** [comment] 2017-10-25 18:24
This sounds a bit like my [LunarG issue #711](https://vulkan.lunarg.com/issue/view/59b3df0ce46ffe6c0d3db02c).

**Comment by CrisBRM** [comment] 2017-10-25 18:50
@eloj it was a kernel issue. Simply appending radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1 to my kernel commandline fixed the issue.

**Comment by xlpiao** [comment] 2018-02-01 14:55
@CrisBRM 
Hi, Cris.
I have the same issue. 

The graphic card that I am testing now is
`[AMD/ATI] Venus LE / Tropo PRO-L [Radeon HD 8830M / R7 M465X] (rev 87)`

Above, you said it was a kernel issue. What do you mean by appending  `radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1` to the commandline ? 

Do you mean that I should add `radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1` to `/etc/default/grub` and `update-grub` ?
