### ISSUE TITLE
Cannnot make for android with MinGW

### ISSUE THREAD

**Issue by chakmeshma** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2229] opened 2017-11-24 16:26 UTC
I first set environment variables:
```
export ANDROID_SDK_HOME="C:/Users/chakm/AppData/Local/Android/sdk"
export ANDROID_NDK_HOME="C:/Users/chakm/AppData/Local/Android/sdk/ndk-bundle"
export PATH=$ANDROID_SDK_HOME:$PATH
export PATH=$ANDROID_NDK_HOME:$PATH
export PATH="/c/Program Files/Android/Android Studio/jre/bin/":$PATH
export PATH="/c/Users/chakm/AppData/Local/Android/sdk/build-tools/26.0.2/":$PATH
export PATH="/c/Users/chakm/AppData/Local/Android/sdk/ndk-bundle/build/":$PATH
```

Then inside MinGW i do:
build-android/build_all.sh

I get the following errors:
```
update_external_sources_android.sh finished.
./android-generate.sh
* Building vk_safe_struct.h
* Generated vk_safe_struct.h
* Building vk_safe_struct.cpp
* Generated vk_safe_struct.cpp
* Building vk_struct_size_helper.h
* Generated vk_struct_size_helper.h
* Building vk_struct_size_helper.c
* Generated vk_struct_size_helper.c
* Building vk_enum_string_helper.h
* Generated vk_enum_string_helper.h
* Building vk_object_types.h
* Generated vk_object_types.h
* Building vk_dispatch_table_helper.h
* Generated vk_dispatch_table_helper.h
* Building thread_check.h
* Generated thread_check.h
* Building parameter_validation.cpp
* Generated parameter_validation.cpp
* Building unique_objects_wrappers.h
* Generated unique_objects_wrappers.h
* Building vk_loader_extensions.h
* Generated vk_loader_extensions.h
* Building vk_loader_extensions.c
* Generated vk_loader_extensions.c
* Building vk_layer_dispatch_table.h
* Generated vk_layer_dispatch_table.h
* Building vk_extension_helper.h
* Generated vk_extension_helper.h
* Building object_tracker.cpp
* Generated object_tracker.cpp
* Building vk_typemap_helper.h
* Generated vk_typemap_helper.h

ndk-build -j 4
/bin/sh: rem: command not found
make: *** [/c/Users/chakm/AppData/Local/Android/sdk/ndk-bundle/build/core/build-binary.mk:534: obj/local/armeabi-v7a/objs/layer_utils/__/__/layers] Error 127
/bin/sh: rem: command not found
make: *** Waiting for unfinished jobs....
make: *** [/c/Users/chakm/AppData/Local/Android/sdk/ndk-bundle/build/core/build-binary.mk:534: obj/local/armeabi-v7a/objs/VkLayer_core_validation/__/__/layers] Error 127
/bin/sh: rem: command not found
make: *** [/c/Users/chakm/AppData/Local/Android/sdk/ndk-bundle/build/core/build-binary.mk:534: obj/local/armeabi-v7a/objs/glslang/glslang/GenericCodeGen] Error 127
/bin/sh: rem: command not found
make: *** [/c/Users/chakm/AppData/Local/Android/sdk/ndk-bundle/build/core/build-binary.mk:534: obj/local/armeabi-v7a/objs/glslang/glslang/MachineIndependent] Error 127

```

**Comment by cnorthrop** [comment] 2017-11-27 16:37
We don't support MinGW builds.  If you would like to provide patches or documentation that get it working, we can try to get them in.  Preferably it would work for desktop and Android builds.

**Comment by krOoze** [comment] 2017-11-27 17:21
@chakmeshma Out of curiosity: Is it supposed to work? MinGW is usually intended for targets that are Windows.

**Comment by mark-lunarg** [comment] 2017-11-29 14:57
As this is intended behavior, can we close this issue @chakmeshma , @cnorthrop?

**Closed** 2017-11-29 17:32 UTC
Labels: help wanted
