### ISSUE TITLE
Why are the Loader and Validation Layers combined in the same repo?

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-LoaderAndValidationLayers#2458] opened 2018-03-01 20:44 UTC
This issue was originally submitted to the Ecosystem github as [issue #22](https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/22). To read the full detail and discussion on this issue, refer to it on the Ecosystem github.

After discussion within the ecosystem forum it was determined that the issue should be moved to this project to handle implementation. 

The original issue text:

> Vulkan Loader and validation layers seem separate to me.
> 
> Validation Layers are a critical part of developer productivity when working with Vulkan. But its just "a" layer, abeit an important part.
> 
> Loader is a much more intrinsic part of vulkan and defines how we bring layers up.
> 
> They are in one repo for historic reasons. Maybe they should be separate repos? It strikes me that merged as they are, we talk a lot about validation issues because those are things developers are passionate about, but forget to talk about loader issues, of which there are many and, arguably just as important. By getting these into separate repos, my instinct says we can start talking about these as distinct things both needing our time and energy.

**Comment by jjulianoatnv** [comment] 2018-03-13 14:16
I do not see value that would be gained by separating loader and layers into separate repos. The stated "forget to talk about" is not really caused by whether there is one repo or two separate repos. There is already a label for "loader". Perhaps what's being requested is a separate (new) label for "layers".

**Comment by jzulauf-lunarg** [comment] 2018-04-02 17:07
This is now being tracked in #2533 . Closing this issue to redirect all comments to that one.

**Closed by jzulauf-lunarg** 2018-04-02 17:07 UTC
Labels: enhancement
