### ISSUE TITLE
SC layer: Tessellation evaluation to geometry shader interface error

### ISSUE THREAD

**Issue by yavn** [KhronosGroup/Vulkan-LoaderAndValidationLayers#377] opened 2016-04-18 09:24 UTC
It seems there's one more interface mismatch case when dealing with user defined IO block:

```
// tessellation evaluation

layout(location = 0) out VertexData {
    vec4 in_gs_tessCoord;
    int  in_gs_primitiveID;
} ib_out;
```

```
// geometry

layout(location = 0) in VertexData {
    vec4 in_gs_tessCoord;
    int  in_gs_primitiveID;
} ib_in[];
```

I'm getting the following errors:

> SC(ERROR): object: 0 type: 0 location: 1545 msgCode: 1: Type mismatch on location 0.0: 'vec4 of float32' vs 'vec4 of float32'
> SC(ERROR): object: 0 type: 0 location: 1545 msgCode: 1: Type mismatch on location 1.0: 'sint32' vs 'sint32'

Here TESE output is not arrayed, but GEOM input is, and the arrayness is at the block level rather than block member. It seems this case is not covered by `types_match()` function.

Example test is available in CTS branch `302-tessellation-shader-tests` test group `dEQP-VK.tessellation.invariance`. More complex IO blocks are in `dEQP-VK.tessellation.user_defined_io`.

**Comment by FslNopper** [comment] 2016-04-19 10:19
Did you test with the latest master branch? I had the same issue with 1.0.8, but it is seems to be fixed now.

**Comment by yavn** [comment] 2016-04-19 10:43
Just tested with the latest master, and yes it still happens. Perhaps some other mismatch situation was fixed. I remember getting TESC into TESE errors before and these are fixed I think, but now it's TESE into GEOM.

**Comment by chrisforbes** [comment] 2016-04-20 01:37
Looking into this.

**Comment by chrisforbes** [comment] 2016-04-20 01:38
Right, the problem is the additional array level is not expressed in the member type -- it's in the block type. types_match is still looking for one to throw away, though.

**Comment by chrisforbes** [comment] 2016-04-20 01:49
Fix in #389 will solve this for reasonable cases. We'll miss producing errors for cases around arrays of blocks which aren't arrays of vertices -- but that's a crazy edge case.

**Comment by chrisforbes** [comment] 2016-04-20 21:41
Fixed in master.

**Closed by chrisforbes** 2016-04-20 21:41 UTC
Labels: bug

**Comment by yavn** [comment] 2016-04-21 08:00
Works for me, thanks!
