### ISSUE TITLE
Installing VK Runtime removes all debug layer entries in windows registry

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-LoaderAndValidationLayers#883] opened 2016-08-24 17:37 UTC
Hi,

for some unknown reason on my system the installer that updates the Vulkan loader (either that one that comes with an driver update or via the sdk), removes the entries in the windows registry of all explicite layers. Which forces me to add those entries back every the time when a driver/sdk update starts the Vulkan installer.

The entries of the implicit layers is not changed.

Happens on Windows 10 64Bit

**Comment by lenny-lunarg** [comment] 2016-08-24 17:50
This may be intended behavior, depending on the exact nature of the layers that were removed. If you install a version of the vulkan runtime (which is included in both the drivers and SDK) that is more recent than any SDK that you have installed, then all explicit layers that were installed by the SDK will be removed. The runtime installer shouldn't remove any entries that weren't pointing to an SDK installation.

The reason we did this was that we were worried that if you install a newer version of the runtime than you have an SDK for, there may be compatibility issues. That being said, we were discussing this internally a week or two ago, and I think we were feeling like we shouldn't do this for every release. We may want to keep doing it for updates to the API major or minor version, but likely not for patch versions. That being said, I don't think we ever came to a definite conclusions, except that we'd leave it as is for the moment.

So the question here is, what runtime installer version is being run, what sdk version do you have, and were there any layers removed that didn't come from an SDK? You may be able to get around the issues by just installing the latest SDK, but even if that's the case, we may want to change this behavior.

**Comment by TiemoJung** [comment] 2016-08-24 17:54
Just installed sdk v. 1.0.21.1 again and it removed all explicit layers and inserted none.

**Comment by lenny-lunarg** [comment] 2016-08-24 18:04
Well then that's definitely a bug. When you installed and uninstalled the runtime, it should write a couple of log files to the temp directory. Would you mind attaching those files for me?

To locate them, open a file explorer and enter `%TEMP%\VulkanRT` into the address bar. Just upload everything in that directory. If the directory is empty, re-run the installer (the temp directory gets cleared out periodically). If it's still empty, then something weird is going on.

**Comment by TiemoJung** [comment] 2016-08-24 18:06
Here you go.
[VulkanRT.zip](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/435368/VulkanRT.zip)

**Comment by lenny-lunarg** [comment] 2016-08-24 19:42
It looks like what's happening is that there is powershell script in the installer, which is responsible for managing vulkan-1.dll and vulkaninfo.exe, and that script is failing. To be honest, the behavior for that script in your log file makes no sense whatsoever. That being said, that powershell script has been causing us problems for ages, so we're replacing it in the next sdk update. 

I've attached a pre-release of the Vulkan runtime installer that has the powershell script removed and uses its own program to perform the same tasks. Note that this won't set the layers for your SDK when you install it, but when you uninstall it, the runtime should be able to detect what's installed on your system and reconfigure everything. As a result, you'll need to install and uninstall this runtime (the uninstaller should be located in `C:\Program Files (x86)\VulkanRT\1.0.21.2.ccvb.1352\`). Hopefully that will fix your problem. If you need, I can probably also send you the corresponding pre-release SDK, but it's a little over 100 MB, so I can't just post it github without getting a little tricky.

If it doesn't fix it, would you mind resending the log files like before (they should have changed a bit)?

[VulkanRT-1.0.21.2.ccvb.1352-Installer.zip](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/files/435534/VulkanRT-1.0.21.2.ccvb.1352-Installer.zip)

**Comment by krOoze** [comment] 2016-08-25 00:20
Yeah, it broke with the Windows 10 1607 update for me. Now on every uninstall it shows some dialog of powershell error and layers are never installed back. It is reported on Lunar Xchange too for some time.

Unfortunately your workaround installer doesn't even seem to try to populate the layer registry. Is it supposed to be called with some parameters or something?

Anyway I created simple *.bat workaround that populates the registry using `VULKAN_SDK` env variable: https://github.com/krOoze/layer_registry_workaround

**Comment by TiemoJung** [comment] 2016-08-25 11:15
After uninstalling the provided pre release installer it fixes the registry entries. Thanks!

**Comment by TiemoJung** [comment] 2016-08-25 11:21
Addition: The uninstaller that fixes the entries in the registry also adds VkLayer_vktrace_layer.json which it should not. It breaks other layers if it is added to ExplicitLayers key.

**Comment by lenny-lunarg** [comment] 2016-08-25 16:03
@TiemoJung, I'm glad this runtime version worked, but I'm a little confused what you mean by saying that VkLayer_vktrace_layer.json shouldn't be added to the explicit layers. It's being added, and this is intentional, but I don't see how it would break other layers unless you enable it. It's also necessary for vktrace to function properly.

@krOoze, Just to clarify, when you uninstalled the runtime I posted above, did that fix things? Because we're trying to make sure there's as few bugs as possible before we release it and I'd like to know if it fails.

**Comment by TiemoJung** [comment] 2016-08-25 16:09
Never mind, was a mistake. Works just fine as it seems.

**Comment by krOoze** [comment] 2016-08-25 16:09
@lenny-lunarg Yeah, it works. I just did not expect I am supposed to uninstall it.

**Comment by lenny-lunarg** [comment] 2016-08-25 16:11
Ok, sounds like this is all working now and that the next release should have this fixed, so I'm closing this issue.

**Closed by lenny-lunarg** 2016-08-25 16:11 UTC
